-- 1 에서  178  행에 대한 삽입 실패
--ORA-01722: invalid number
--행 1
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'스칸디아모스 토피어리 습도조절 천연이끼 화분장식소품',25500,'/resources/image/flower-images/comment/air-purifying-plants_01_comment.PNG',707,to_date('05/17/2022', 'MM/DD/RRRR'),'Y','N',10,'N','Y',5,6);
--행 2
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'살아있는 스칸디아모스 트리 화분 2size',37000,'/resources/image/flower-images/comment/air-purifying-plants_02_comment.PNG',602,to_date('12/18/2022', 'MM/DD/RRRR'),'N','N',9,'Y','Y',1,6);
--행 3
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'문샤인 키우기 쉬운 공기정화식물 책상용화분 음이온',29000,'/resources/image/flower-images/comment/air-purifying-plants_03_comment.PNG',416,to_date('09/25/2021', 'MM/DD/RRRR'),'Y','N',3,'N','Y',9,6);
--행 4
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'천연가습기 수경재배식물 빅토리아',27000,'/resources/image/flower-images/comment/air-purifying-plants_04_comment.PNG',375,to_date('08/28/2022', 'MM/DD/RRRR'),'N','Y',77,'Y','N',3,6);
--행 5
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'수염틸란드시아 미세먼지정화 실내공기정화 행잉플랜트',13900,'/resources/image/flower-images/comment/air-purifying-plants_05_comment.PNG',154,to_date('04/23/2022', 'MM/DD/RRRR'),'Y','Y',35,'N','N',2,6);
--행 6
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'모여라 공기정화식물 화분',9800,'/resources/image/flower-images/comment/air-purifying-plants_06_comment.PNG',228,to_date('01/13/2021', 'MM/DD/RRRR'),'N','Y',68,'Y','N',9,6);
--행 7
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'라푼젤 아이비 공기정화식물 행잉플랜트',24000,'/resources/image/flower-images/comment/air-purifying-plants_07_comment.PNG',526,to_date('05/29/2022', 'MM/DD/RRRR'),'Y','N',7,'N','Y',6,6);
--행 8
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'공기정화식물 아래로 드랍되면서 크는 초록이 디시디아',17000,'/resources/image/flower-images/comment/air-purifying-plants_08_comment.PNG',398,to_date('12/31/2022', 'MM/DD/RRRR'),'N','N',21,'Y','Y',7,6);
--행 9
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'스투키 핑크화분 핑크라마',15000,'/resources/image/flower-images/comment/air-purifying-plants_09_comment.PNG',50,to_date('02/20/2022', 'MM/DD/RRRR'),'Y','N',22,'N','Y',10,6);
--행 10
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'공기정화식물 빈티지 우드 사각화분',20000,'/resources/image/flower-images/comment/air-purifying-plants_10_comment.PNG',277,to_date('01/08/2021', 'MM/DD/RRRR'),'N','Y',19,'Y','N',6,6);
--행 11
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'아기 수달 토피어리',15900,'/resources/image/flower-images/comment/air-purifying-plants_11_comment.PNG',790,to_date('03/07/2021', 'MM/DD/RRRR'),'Y','Y',83,'N','N',10,6);
--행 12
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'올리브나무 토피어리 실내식물 공기정화식물 외목대',25000,'/resources/image/flower-images/comment/air-purifying-plants_12_comment.PNG',106,to_date('08/31/2021', 'MM/DD/RRRR'),'N','Y',15,'Y','N',2,6);
--행 13
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'먼지먹는식물,에어플랜트마크라메파인애플,틸란드시아',19000,'/resources/image/flower-images/comment/air-purifying-plants_13_comment.PNG',620,to_date('10/01/2022', 'MM/DD/RRRR'),'Y','N',77,'N','Y',4,6);
--행 14
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'함박자스민,공기정화식물,식물인테리어,플랜테리어',14800,'/resources/image/flower-images/comment/air-purifying-plants_14_comment.PNG',164,to_date('05/28/2022', 'MM/DD/RRRR'),'N','N',7,'Y','Y',8,6);
--행 15
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'실내공기정화식물 해피트리, 미니화분',22000,'/resources/image/flower-images/comment/air-purifying-plants_15_comment.PNG',42,to_date('07/09/2021', 'MM/DD/RRRR'),'Y','N',67,'N','Y',8,6);
--행 16
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'튤립 조화 꽃 장식 망고튤립조화 소프트튤립 핑크 꽃다발 셀프웨딩 부케 실크플라워',5000,'/resources/image/flower-images/comment/artificial_01_comment.PNG',310,to_date('02/12/2017', 'MM/DD/RRRR'),'N','N',27,'Y','Y',4,12);
--행 17
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'봄꽃 인테리어 소품 성묘조화',2000,'/resources/image/flower-images/comment/artificial_02_comment.PNG',300,to_date('09/23/2016', 'MM/DD/RRRR'),'Y','Y',73,'Y','Y',5,12);
--행 18
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'폼폼 가을 봄꽃 실크플라워 꽃꽂이',4000,'/resources/image/flower-images/comment/artificial_03_comment.PNG',200,to_date('05/29/2021', 'MM/DD/RRRR'),'Y','Y',26,'N','Y',3,12);
--행 19
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'거베라 조화 한송이 가지 2컬러 실크플라워 꽃꽂이재료 꽃장식 꽃다발',60000,'/resources/image/flower-images/comment/artificial_04_comment.PNG',500,to_date('12/05/2019', 'MM/DD/RRRR'),'N','Y',25,'Y','N',4,12);
--행 20
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'화분 데코장식',5000,'/resources/image/flower-images/comment/artificial_05_comment.PNG',400,to_date('02/12/2017', 'MM/DD/RRRR'),'N','Y',71,'Y','Y',4,12);
--행 21
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'인조 리얼이끼 조화 조경 플랜트박스 조화나무 데코 셀프인테리어 플랜테리어',45000,'/resources/image/flower-images/comment/artificial_06_comment.PNG',250,to_date('09/14/2018', 'MM/DD/RRRR'),'N','Y',14,'N','N',3,12);
--행 22
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'측백 조화나무 인조화분 생화같은 인테리어 인조나무 오피스',3200,'/resources/image/flower-images/comment/artificial_07_comment.PNG',300,to_date('02/12/2017', 'MM/DD/RRRR'),'Y','Y',59,'N','Y',2,12);
--행 23
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'유주 레몬 조화나무 인테리어 인조화분 거실 카페 장식 식물 유주나무',1200,'/resources/image/flower-images/comment/artificial_08_comment.PNG',120,to_date('02/12/2017', 'MM/DD/RRRR'),'Y','N',60,'Y','Y',2,12);
--행 24
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'생화같은 고급 리얼 자나장미 조화꽃장식(3color)',6500,'/resources/image/flower-images/comment/artificial_09_comment.PNG',320,to_date('09/23/2016', 'MM/DD/RRRR'),'N','Y',11,'N','N',2,12);
--행 25
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'생화같은 해바라기 조화꽃 금전운 인테리어',5000,'/resources/image/flower-images/comment/artificial_10_comment.PNG',400,to_date('12/26/2019', 'MM/DD/RRRR'),'Y','Y',22,'Y','Y',4,12);
--행 26
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'엔드텔러 플랜트월 인테리어 조화 벽면녹화 수직정원 몬스테라인조 그린월 꽃벽',4000,'/resources/image/flower-images/comment/artificial_11_comment.PNG',100,to_date('05/20/2018', 'MM/DD/RRRR'),'Y','N',13,'Y','N',3,12);
--행 27
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'엔드텔러 행잉플랜트 담쟁이 넝쿨 조화 소품 인조 넝쿨',3000,'/resources/image/flower-images/comment/artificial_12_comment.PNG',200,to_date('02/12/2017', 'MM/DD/RRRR'),'N','Y',84,'N','N',2,12);
--행 28
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'졸업식 자이언트 장미꽃다발 화이트데이 인싸템',24900,'/resources/image/flower-images/comment/bouquet_01_comment.PNG',73,to_date('06/15/2022', 'MM/DD/RRRR'),'N','Y',42,'Y','N',10,2);
--행 29
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'이벤트 선물 투톤 안개 장미 레터링 장미 꽃다발 강추',13900,'/resources/image/flower-images/comment/bouquet_02_comment.PNG',853,to_date('05/25/2022', 'MM/DD/RRRR'),'Y','Y',96,'N','N',2,2);
--행 30
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'크게리뉴얼 안개꽃 서비스 시들지않는 무지개 장미 꽃다발',10900,'/resources/image/flower-images/comment/bouquet_03_comment.PNG',922,to_date('02/08/2023', 'MM/DD/RRRR'),'N','Y',11,'Y','N',6,2);
--행 31
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'시들지않은 수국꽃다발 프리저브드 꽃다발',28900,'/resources/image/flower-images/comment/bouquet_04_comment.PNG',27,to_date('09/10/2022', 'MM/DD/RRRR'),'Y','N',95,'N','Y',7,2);
--행 32
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'오로라장미 꽃다발 꽃말: 영원한 사랑',18000,'/resources/image/flower-images/comment/bouquet_05_comment.PNG',37,to_date('10/16/2022', 'MM/DD/RRRR'),'N','N',7,'Y','Y',1,2);
--행 33
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'생화 시즈널 렌덤 플라워 세트',13900,'/resources/image/flower-images/comment/bouquet_06_comment.PNG',445,to_date('01/06/2022', 'MM/DD/RRRR'),'Y','N',69,'N','Y',5,2);
--행 34
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'한송이 스마일인형 꽃다발 졸업식꽃다발 단체선물 인형꽃',3500,'/resources/image/flower-images/comment/bouquet_07_comment.PNG',631,to_date('04/06/2021', 'MM/DD/RRRR'),'N','Y',88,'Y','N',2,2);
--행 35
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'졸업식꽃다발 스마일 퐁퐁꽃다발',18000,'/resources/image/flower-images/comment/bouquet_08_comment.PNG',114,to_date('09/19/2022', 'MM/DD/RRRR'),'Y','Y',82,'N','N',8,2);
--행 36
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'화이트데이기획전 오랫동안 볼수있는 시들지않는 꽃다발',10900,'/resources/image/flower-images/comment/bouquet_09_comment.PNG',802,to_date('04/10/2022', 'MM/DD/RRRR'),'N','Y',84,'Y','N',1,2);
--행 37
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'명품 샤미 꽃다발 프리저브드 화이트 장미꽃다발',25900,'/resources/image/flower-images/comment/bouquet_10_comment.PNG',215,to_date('06/03/2022', 'MM/DD/RRRR'),'Y','N',78,'N','Y',4,2);
--행 38
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'졸업식꽃다발 자이언트 카네이션 꽃다발 인싸템 화이트데이',24900,'/resources/image/flower-images/comment/bouquet_11_comment.PNG',396,to_date('03/07/2021', 'MM/DD/RRRR'),'N','N',68,'Y','Y',2,2);
--행 39
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'자나장미 꽃다발 50,100송이 생화',38900,'/resources/image/flower-images/comment/bouquet_12_comment.PNG',620,to_date('12/19/2021', 'MM/DD/RRRR'),'Y','N',70,'N','Y',1,2);
--행 40
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'고급쇼핑백포함 장미 50송이 100송이 대형꽃다발선물',39900,'/resources/image/flower-images/comment/bouquet_13_comment.PNG',501,to_date('09/30/2021', 'MM/DD/RRRR'),'N','Y',46,'Y','N',3,2);
--행 41
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'생화 스토크 꽃다발',28000,'/resources/image/flower-images/comment/bouquet_14_comment.PNG',448,to_date('03/16/2021', 'MM/DD/RRRR'),'Y','Y',15,'N','N',7,2);
--행 42
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'시들지 않는 영롱한 색감의 수선화 꽃다발',8000,'/resources/image/flower-images/comment/bouquet_15_comment.PNG',757,to_date('04/06/2021', 'MM/DD/RRRR'),'N','Y',99,'Y','N',3,2);
--행 43
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'근조 3단 화환',59000,NULL,200,to_date('12/07/2019', 'MM/DD/RRRR'),'N','Y',87,'Y','N',4,4);
--행 44
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'노란리본 근조 화환',75000,NULL,150,to_date('12/25/2022', 'MM/DD/RRRR'),'N','Y',90,'Y','N',4,4);
--행 45
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'근조 고급 3단 화환',79000,NULL,150,to_date('11/28/2019', 'MM/DD/RRRR'),'N','Y',62,'Y','N',3,4);
--행 46
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'근조 특대 3단 화환',99000,NULL,200,to_date('05/29/2021', 'MM/DD/RRRR'),'N','Y',62,'Y','Y',2,4);
--행 47
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'근조 5단 화환',220000,'/resources/image/flower-images/condolences-wreath/condolences-wreath_05/spec01.PNG',250,to_date('02/10/2022', 'MM/DD/RRRR'),'N','Y',40,'Y','Y',2,4);
--행 48
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'근조화환',48000,NULL,100,to_date('12/05/2019', 'MM/DD/RRRR'),'N','Y',5,'N','Y',2,4);
--행 49
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'오브제 근조화환',50000,NULL,300,to_date('02/12/2017', 'MM/DD/RRRR'),'N','Y',24,'N','N',4,4);
--행 50
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'근조 3단 화환 <특가>',45000,'/resources/image/flower-images/condolences-wreath/condolences-wreath_08/spec01.PNG',500,to_date('09/14/2018', 'MM/DD/RRRR'),'N','Y',78,'Y','N',5,4);
--행 51
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'영정바구니',49000,NULL,200,to_date('02/14/2022', 'MM/DD/RRRR'),'N','Y',40,'Y','N',3,4);
--행 52
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'특가 근조 3단 A',50000,'/resources/image/flower-images/condolences-wreath/condolences-wreath_10/spec01.PNG',150,to_date('02/12/2017', 'MM/DD/RRRR'),'N','Y',36,'Y','Y',4,4);
--행 53
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'고급 근조 3단',99000,NULL,350,to_date('09/23/2016', 'MM/DD/RRRR'),'N','Y',71,'Y','Y',8,4);
--행 54
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'프리미엄 근조화환 4단',150000,'/resources/image/flower-images/condolences-wreath/condolences-wreath_12/spec01.PNG',100,to_date('08/31/2021', 'MM/DD/RRRR'),'N','Y',62,'Y','Y',10,4);
--행 55
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'근조바구니',58000,'/resources/image/flower-images/condolences-wreath/condolences-wreath_13/spec01.PNG',500,to_date('10/01/2022', 'MM/DD/RRRR'),'N','Y',65,'Y','Y',2,4);
--행 56
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'근조 기업형 화환',95000,'/resources/image/flower-images/condolences-wreath/condolences-wreath_14/spec01.PNG',250,to_date('05/28/2022', 'MM/DD/RRRR'),'N','Y',2,'N','Y',6,4);
--행 57
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'블랙 금박리본 근조 화환',99000,NULL,200,to_date('07/09/2021', 'MM/DD/RRRR'),'N','Y',56,'N','Y',7,4);
--행 58
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 프리미엄 화환 <특가>',189000,NULL,200,to_date('06/15/2022', 'MM/DD/RRRR'),'N','Y',17,'Y','Y',8,3);
--행 59
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 특대 3단 화환',99000,NULL,150,to_date('05/25/2020', 'MM/DD/RRRR'),'N','Y',69,'Y','Y',8,3);
--행 60
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 특특대 3단 화환',149000,NULL,150,to_date('02/08/2023', 'MM/DD/RRRR'),'N','Y',98,'Y','Y',10,3);
--행 61
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 골드 화환',220000,'/resources/image/flower-images/congratulatory-wreath/congratulatory-wreath_04/spec01.PNG',200,to_date('09/10/2022', 'MM/DD/RRRR'),'N','Y',39,'Y','Y',2,3);
--행 62
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 오브제 1단 화환',100000,'/resources/image/flower-images/congratulatory-wreath/congratulatory-wreath_05/spec01.PNG',250,to_date('10/16/2022', 'MM/DD/RRRR'),'N','Y',80,'Y','Y',6,3);
--행 63
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축화화환',48000,NULL,100,to_date('01/06/2022', 'MM/DD/RRRR'),'N','Y',47,'Y','N',7,3);
--행 64
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 3단 화환 <특가>',75000,NULL,300,to_date('11/15/2018', 'MM/DD/RRRR'),'N','Y',36,'Y','N',1,3);
--행 65
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 3단 A',55000,'/resources/image/flower-images/congratulatory-wreath/congratulatory-wreath_08/spec01.PNG',500,to_date('02/14/2019', 'MM/DD/RRRR'),'N','Y',63,'N','Y',5,3);
--행 66
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'포인트 축하 3단',49000,'/resources/image/flower-images/congratulatory-wreath/congratulatory-wreath_09/spec01.PNG',200,to_date('07/11/2021', 'MM/DD/RRRR'),'N','Y',66,'N','Y',2,3);
--행 67
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 오브제 화환',209000,NULL,150,to_date('12/05/2019', 'MM/DD/RRRR'),'N','Y',28,'Y','Y',8,3);
--행 68
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 화환 5단',199500,NULL,350,to_date('07/01/2019', 'MM/DD/RRRR'),'N','Y',48,'Y','N',1,3);
--행 69
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 4단 화환',155000,NULL,100,to_date('09/14/2018', 'MM/DD/RRRR'),'N','Y',25,'Y','N',4,3);
--행 70
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 화환 대형',100000,NULL,500,to_date('02/12/2017', 'MM/DD/RRRR'),'N','Y',6,'Y','N',4,3);
--행 71
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 3단 특대형',150000,NULL,250,to_date('09/27/2022', 'MM/DD/RRRR'),'N','Y',48,'Y','Y',3,3);
--행 72
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'축하 3단 클래식 화환',59000,'/resources/image/flower-images/congratulatory-wreath/congratulatory-wreath_15/spec01.PNG',200,to_date('08/13/2019', 'MM/DD/RRRR'),'N','Y',4,'Y','Y',2,3);
--행 73
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'웨딩 꽃바구니',55000,'/resources/image/flower-images/flower-basket/flower-basket_01/07.PNG',1,to_date('02/10/2023', 'MM/DD/RRRR'),'Y','N',84,'Y','Y',2,1);
--행 74
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'퍼플 꽃바구니',35000,'/resources/image/flower-images/flower-basket/flower-basket_02/07.PNG',36,to_date('12/30/2019', 'MM/DD/RRRR'),'N','N',10,'N','Y',6,1);
--행 75
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'미니박스 꽃바구니',28000,'/resources/image/flower-images/flower-basket/flower-basket_03/08.PNG',61,to_date('09/15/2019', 'MM/DD/RRRR'),'N','N',57,'N','Y',10,1);
--행 76
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'핑크선플라워 꽃바구니',30000,'/resources/image/flower-images/flower-basket/flower-basket_04/07.PNG',17,to_date('10/13/2020', 'MM/DD/RRRR'),'Y','Y',81,'N','Y',10,1);
--행 77
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'로즈오울 꽃바구니',45000,'/resources/image/flower-images/flower-basket/flower-basket_05/08.PNG',39,to_date('06/18/2023', 'MM/DD/RRRR'),'Y','Y',93,'Y','Y',9,1);
--행 78
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'수국장미 꽃바구니',60000,'/resources/image/flower-images/flower-basket/flower-basket_06/10.PNG',83,to_date('07/16/2019', 'MM/DD/RRRR'),'Y','Y',17,'N','Y',4,1);
--행 79
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'안개속의 장미 꽃바구니',55000,'/resources/image/flower-images/flower-basket/flower-basket_07/10.PNG',94,to_date('03/10/2020', 'MM/DD/RRRR'),'N','Y',62,'Y','Y',5,1);
--행 80
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'햇살속의 핑크장미 꽃바구니',71000,'/resources/image/flower-images/flower-basket/flower-basket_08/10.PNG',85,to_date('04/20/2022', 'MM/DD/RRRR'),'Y','N',54,'Y','Y',9,1);
--행 81
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'프리지아 꽃바구니',90000,'/resources/image/flower-images/flower-basket/flower-basket_09/10.PNG',1,to_date('04/28/2021', 'MM/DD/RRRR'),'N','N',73,'N','Y',5,1);
--행 82
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'아름다운 기도 꽃바구니',62000,'/resources/image/flower-images/flower-basket/flower-basket_10/10.PNG',49,to_date('02/25/2019', 'MM/DD/RRRR'),'Y','Y',80,'Y','Y',7,1);
--행 83
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'봄내음 프리지아 꽃바구니',70000,'/resources/image/flower-images/flower-basket/flower-basket_11/10.PNG',68,to_date('07/02/2023', 'MM/DD/RRRR'),'N','N',53,'N','Y',8,1);
--행 84
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'샛노란 프리지아 꽃바구니',67000,'/resources/image/flower-images/flower-basket/flower-basket_12/10.PNG',90,to_date('11/29/2019', 'MM/DD/RRRR'),'Y','Y',45,'Y','Y',1,1);
--행 85
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'노란 고백 꽃바구니',58000,'/resources/image/flower-images/flower-basket/flower-basket_13/10.PNG',79,to_date('02/19/2021', 'MM/DD/RRRR'),'N','N',5,'N','Y',5,1);
--행 86
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'프리지아 장미하트 꽃바구니',82000,'/resources/image/flower-images/flower-basket/flower-basket_14/10.PNG',56,to_date('07/22/2021', 'MM/DD/RRRR'),'Y','Y',31,'Y','Y',4,1);
--행 87
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'프리지아 장미 혼합 꽃바구니',54000,'/resources/image/flower-images/flower-basket/flower-basket_15/10.PNG',41,to_date('09/18/2021', 'MM/DD/RRRR'),'Y','N',70,'N','Y',3,1);
--행 88
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'몬스테라,테이블야자 수경재배식물 라탄화병세트',26800,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_01/spec01.PNG',22,to_date('09/15/2022', 'MM/DD/RRRR'),'Y','N',58,'N','Y',10,9);
--행 89
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'트리안 수경재배 세트',16800,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_02/spec01.PNG',9,to_date('11/09/2021', 'MM/DD/RRRR'),'Y','N',33,'N','Y',6,9);
--행 90
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'수경식물 재배 유리화기 물에서키우는 스노우사파이어',30000,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_03/spec01.PNG',6,to_date('11/14/2021', 'MM/DD/RRRR'),'Y','Y',80,'Y','N',2,9);
--행 91
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'파인애플선인장(괴마옥),멕시코소철,몬스테라 수경화분세트',27800,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_04/spec01.PNG',41,to_date('02/16/2022', 'MM/DD/RRRR'),'Y','Y',86,'Y','Y',6,9);
--행 92
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'파비안,바로크 벤자민고무나무,파티오라금 전구화병세트',21800,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_05/spec01.PNG',69,to_date('06/24/2023', 'MM/DD/RRRR'),'Y','Y',52,'Y','Y',2,9);
--행 93
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'[할인] 나는 아이비입니다',17900,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_06/spec01.PNG',75,to_date('10/15/2019', 'MM/DD/RRRR'),'N','N',32,'N','N',3,9);
--행 94
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'볼수록 매력적인 이단소니 수경재배세트',17000,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_07/spec01.PNG',67,to_date('12/23/2020', 'MM/DD/RRRR'),'N','N',17,'N','N',9,9);
--행 95
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'스킨답서스 앤틱다이아몬드 수경재배식물 미니화분',24500,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_08/spec01.PNG',67,to_date('09/21/2021', 'MM/DD/RRRR'),'Y','Y',8,'Y','N',10,9);
--행 96
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'싱고니움 수경재배 세트',15800,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_09/spec01.PNG',78,to_date('02/16/2021', 'MM/DD/RRRR'),'N','N',6,'Y','N',7,9);
--행 97
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'천연 습도조절 식물 개운죽',10500,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_10/spec01.PNG',67,to_date('12/22/2022', 'MM/DD/RRRR'),'N','Y',69,'N','N',4,9);
--행 98
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'[천연가습기/실내공기정화] 수경재배식물 테이블야자',29000,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_11/spec01.PNG',22,to_date('03/17/2021', 'MM/DD/RRRR'),'N','N',60,'N','Y',7,9);
--행 99
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'피토니아 수경재배 세트',13800,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_12/spec01.PNG',15,to_date('06/25/2019', 'MM/DD/RRRR'),'N','N',17,'N','Y',6,9);
--행 100
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'수경재배 화분 자연석 플랜트스톤(식물미포함)',35000,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_13/spec01.PNG',3,to_date('06/22/2021', 'MM/DD/RRRR'),'Y','N',10,'N','Y',8,9);
--행 101
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'다육식물 테라리움',8000,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_14/spec01.PNG',93,to_date('08/29/2019', 'MM/DD/RRRR'),'Y','Y',67,'Y','N',6,9);
--행 102
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'[할인]유리볼 티 라이트 홀더 아이비',6000,'/resources/image/flower-images/hydroponic-plants/hydroponic-plants_15/spec01.PNG',45,to_date('11/17/2023', 'MM/DD/RRRR'),'N','Y',82,'Y','Y',2,9);
--행 103
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'대훈 투각청자분',120000,'/resources/image/flower-images/oriental-orchids_01/comment.PNG',30,to_date('12/17/2023', 'MM/DD/RRRR'),'N','Y',22,'Y','N',5,7);
--행 104
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'철소심',60000,'/resources/image/flower-images/oriental-orchids_02/comment.PNG',46,to_date('03/20/2020', 'MM/DD/RRRR'),'Y','Y',53,'N','N',7,7);
--행 105
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'금화산',100000,'/resources/image/flower-images/oriental-orchids_03/comment.PNG',56,to_date('01/11/2023', 'MM/DD/RRRR'),'Y','N',55,'N','N',7,7);
--행 106
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'대국 화병백자',79000,'/resources/image/flower-images/oriental-orchids_04/comment.PNG',27,to_date('12/15/2023', 'MM/DD/RRRR'),'Y','Y',52,'N','N',1,7);
--행 107
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'산천보세',80000,'/resources/image/flower-images/oriental-orchids_05/comment.PNG',97,to_date('09/21/2023', 'MM/DD/RRRR'),'Y','Y',86,'N','N',2,7);
--행 108
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'철금기',100000,'/resources/image/flower-images/oriental-orchids_06/comment.PNG',35,to_date('05/27/2021', 'MM/DD/RRRR'),'Y','Y',9,'N','N',5,7);
--행 109
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'옥화',100000,'/resources/image/flower-images/oriental-orchids_07/comment.PNG',98,to_date('03/04/2020', 'MM/DD/RRRR'),'Y','N',93,'N','Y',3,7);
--행 110
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'채홍',80000,'/resources/image/flower-images/oriental-orchids_08/comment.PNG',66,to_date('07/27/2022', 'MM/DD/RRRR'),'Y','Y',81,'N','N',9,7);
--행 111
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'마이관',78000,'/resources/image/flower-images/oriental-orchids_09/comment.PNG',87,to_date('05/07/2020', 'MM/DD/RRRR'),'Y','N',97,'N','Y',8,7);
--행 112
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'천향',77000,'/resources/image/flower-images/oriental-orchids_10/comment.PNG',45,to_date('09/25/2021', 'MM/DD/RRRR'),'Y','Y',78,'N','N',7,7);
--행 113
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'황금일향',220000,'/resources/image/flower-images/oriental-orchids_11/comment.PNG',77,to_date('08/29/2021', 'MM/DD/RRRR'),'N','Y',96,'Y','Y',8,7);
--행 114
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'금침',77000,'/resources/image/flower-images/oriental-orchids_12/comment.PNG',53,to_date('06/12/2023', 'MM/DD/RRRR'),'N','Y',47,'N','N',7,7);
--행 115
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'국향',145000,'/resources/image/flower-images/oriental-orchids_13/comment.PNG',97,to_date('06/24/2022', 'MM/DD/RRRR'),'N','Y',87,'Y','Y',5,7);
--행 116
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'금황',109000,'/resources/image/flower-images/oriental-orchids_14/comment.PNG',33,to_date('11/21/2020', 'MM/DD/RRRR'),'N','Y',23,'Y','Y',4,7);
--행 117
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'일월관 가락지청자',159000,'/resources/image/flower-images/oriental-orchids_15/comment.PNG',85,to_date('10/20/2021', 'MM/DD/RRRR'),'Y','Y',68,'N','Y',7,7);
--행 118
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'주목 분재',35000,'/resources/image/flower-images/potted-plant/potted-plant_01/07.PNG',120,to_date('10/30/2020', 'MM/DD/RRRR'),'Y','Y',30,'Y','N',9,6);
--행 119
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'대나무숲 분재',45000,'/resources/image/flower-images/potted-plant/potted-plant_02/07.PNG',36,to_date('12/03/2020', 'MM/DD/RRRR'),'Y','N',81,'N','N',2,6);
--행 120
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'새 둥지 분재',34000,'/resources/image/flower-images/potted-plant/potted-plant_03/10.PNG',32,to_date('10/22/2021', 'MM/DD/RRRR'),'N','N',46,'N','Y',3,6);
--행 121
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'복숭아 분재',65000,'/resources/image/flower-images/potted-plant/potted-plant_04/08.PNG',39,to_date('12/26/2022', 'MM/DD/RRRR'),'Y','Y',20,'Y','N',9,6);
--행 122
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'바오밥분재',15000,'/resources/image/flower-images/potted-plant/potted-plant_05/10.PNG',43,to_date('04/21/2022', 'MM/DD/RRRR'),'N','N',98,'Y','Y',1,6);
--행 123
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'백명자 야생화 분재',12000,'/resources/image/flower-images/potted-plant/potted-plant_06/07.PNG',72,to_date('07/14/2023', 'MM/DD/RRRR'),'N','N',45,'Y','Y',10,6);
--행 124
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'소나무 분재',120000,'/resources/image/flower-images/potted-plant/potted-plant_07/06.PNG',14,to_date('07/29/2021', 'MM/DD/RRRR'),'N','Y',43,'N','N',8,6);
--행 125
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'황금 자보 분재',60000,'/resources/image/flower-images/potted-plant/potted-plant_08/07.PNG',76,to_date('10/02/2023', 'MM/DD/RRRR'),'Y','N',91,'N','N',4,6);
--행 126
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'섬진백 문인목 분재',150000,'/resources/image/flower-images/potted-plant/potted-plant_09/06.PNG',66,to_date('02/03/2019', 'MM/DD/RRRR'),'N','N',23,'Y','N',4,6);
--행 127
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'인조소나무 부내 대형',300000,'/resources/image/flower-images/potted-plant/potted-plant_10/10.PNG',74,to_date('07/16/2021', 'MM/DD/RRRR'),'N','Y',33,'N','N',3,6);
--행 128
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'팬더 고무나무 분재',100000,'/resources/image/flower-images/potted-plant/potted-plant_11/06.PNG',100,to_date('05/04/2019', 'MM/DD/RRRR'),'Y','Y',53,'Y','Y',8,6);
--행 129
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'인삼팬더 분재',50000,'/resources/image/flower-images/potted-plant/potted-plant_12/06.PNG',96,to_date('04/03/2023', 'MM/DD/RRRR'),'Y','N',32,'N','N',7,6);
--행 130
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'바오밥 팬더 분재',70000,'/resources/image/flower-images/potted-plant/potted-plant_13/06.PNG',14,to_date('04/11/2019', 'MM/DD/RRRR'),'Y','Y',53,'Y','Y',6,6);
--행 131
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'팬더 동백나무 분재',110000,'/resources/image/flower-images/potted-plant/potted-plant_14/06.PNG',19,to_date('05/19/2022', 'MM/DD/RRRR'),'N','N',63,'N','Y',3,6);
--행 132
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'고무나무 분재',90000,'/resources/image/flower-images/potted-plant/potted-plant_15/07.PNG',96,to_date('01/20/2020', 'MM/DD/RRRR'),'N','Y',39,'Y','N',1,6);
--행 133
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'5개월의 기다림, 꾸까 시그니처 세라믹 화병',20000,'/resources/image/flower-images/comment/props_01_comment.PNG',100,to_date('01/15/2020', 'MM/DD/RRRR'),'Y','N',88,'Y','Y',2,13);
--행 134
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'자체로 아름다운, 다이아몬드 커팅 화병',10000,'/resources/image/flower-images/comment/props_02_comment.PNG',150,to_date('01/14/2020', 'MM/DD/RRRR'),'N','Y',73,'Y','N',3,13);
--행 135
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'솜사탕이 떠오르는 링클 스탠드',15000,'/resources/image/flower-images/comment/props_03_comment.PNG',200,to_date('12/26/2019', 'MM/DD/RRRR'),'N','N',79,'Y','Y',3,13);
--행 136
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'다발의 아름다움을 담아낼 소프트 라운드 화병',65200,'/resources/image/flower-images/comment/props_04_comment.PNG',100,to_date('05/20/2018', 'MM/DD/RRRR'),'N','Y',19,'N','Y',4,13);
--행 137
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'꽃을 귀엽게 꾸며주는, 스위트 세라믹 화병',64000,'/resources/image/flower-images/comment/props_05_comment.PNG',300,to_date('02/12/2017', 'MM/DD/RRRR'),'N','Y',30,'Y','N',2,13);
--행 138
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'내추럴한 꽃꽂이를 위한 와일드 스트라이프 화병',20000,'/resources/image/flower-images/comment/props_06_comment.PNG',320,to_date('12/22/2019', 'MM/DD/RRRR'),'Y','Y',71,'Y','Y',3,13);
--행 139
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'다각도 곡선이 독특한, 오팔린 클린 화병',10000,'/resources/image/flower-images/comment/props_07_comment.PNG',100,to_date('02/09/2017', 'MM/DD/RRRR'),'N','Y',98,'N','N',2,13);
--행 140
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'샤프한 느낌의, 샌드글래스 화병',30000,'/resources/image/flower-images/comment/props_08_comment.PNG',260,to_date('12/05/2019', 'MM/DD/RRRR'),'N','Y',5,'N','Y',8,13);
--행 141
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'쿨한 감성 한 스푼, 샤프 커팅 화병',40000,'/resources/image/flower-images/comment/props_09_comment.PNG',400,to_date('11/28/2019', 'MM/DD/RRRR'),'N','Y',19,'Y','Y',3,13);
--행 142
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'[PAUL] 125년 전통의 독일 브랜드 꽃가위',80000,'/resources/image/flower-images/comment/props_10_comment.PNG',260,to_date('05/29/2021', 'MM/DD/RRRR'),'Y','Y',35,'N','N',4,13);
--행 143
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'[필수 도구] 장미 가시제거기',64000,'/resources/image/flower-images/comment/props_11_comment.PNG',210,to_date('05/29/2021', 'MM/DD/RRRR'),'Y','N',49,'Y','Y',4,13);
--행 144
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'[필수 도구] 초급용 꽃가위',20000,'/resources/image/flower-images/comment/props_12_comment.PNG',270,to_date('12/05/2019', 'MM/DD/RRRR'),'N','Y',60,'Y','N',3,13);
--행 145
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'[필수 도구] 중급용 꽃가위',43000,'/resources/image/flower-images/comment/props_13_comment.PNG',310,to_date('02/12/2017', 'MM/DD/RRRR'),'Y','Y',32,'N','N',2,13);
--행 146
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'[디자인 화병] 물방울 유리화병',91000,'/resources/image/flower-images/comment/props_14_comment.PNG',500,to_date('09/14/2018', 'MM/DD/RRRR'),'Y','N',71,'N','N',2,13);
--행 147
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'[주문 제작] 3D SISU 프리미엄 화병(친환경 소재)',100000,'/resources/image/flower-images/comment/props_15_comment.PNG',310,to_date('02/12/2017', 'MM/DD/RRRR'),'Y','N',96,'Y','N',2,13);
--행 148
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'멋진 다육 작품 플랫분',23000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_01/spec01.PNG',1,to_date('05/25/2023', 'MM/DD/RRRR'),'Y','N',62,'N','N',6,11);
--행 149
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'캐주얼미니화분(다육)',7000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_02/spec01.PNG',29,to_date('01/01/2022', 'MM/DD/RRRR'),'Y','Y',3,'Y','Y',9,11);
--행 150
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'미니다육이 미니어처 커피 컵 시리즈',10000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_03/spec01.PNG',4,to_date('11/01/2019', 'MM/DD/RRRR'),'Y','N',82,'Y','Y',9,11);
--행 151
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'캔속의 선인장',6500,'/resources/image/succulent-plant/succulent-plant/succulent-plant_04/spec01.PNG',89,to_date('03/05/2022', 'MM/DD/RRRR'),'Y','Y',26,'Y','Y',7,11);
--행 152
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'미니다육미니선인장독일토분핑거식물',3500,'/resources/image/succulent-plant/succulent-plant/succulent-plant_05/spec01.PNG',56,to_date('12/21/2022', 'MM/DD/RRRR'),'N','N',30,'N','N',8,11);
--행 153
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'귀여운 코알라 화분 이오난사 공중 식물 행잉',20000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_06/spec01.PNG',26,to_date('11/25/2019', 'MM/DD/RRRR'),'Y','N',6,'Y','N',2,11);
--행 154
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'귀여운 코알라 화분 괴마옥 피쉬본 하트호야',40000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_07/spec01.PNG',74,to_date('10/23/2019', 'MM/DD/RRRR'),'Y','Y',4,'N','Y',1,11);
--행 155
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'반려식물 오늘행성시리즈 해왕성 스칸디아모스승진화분',37000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_08/spec01.PNG',98,to_date('05/27/2022', 'MM/DD/RRRR'),'Y','Y',87,'N','Y',9,12);
--행 156
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'[천연이끼] 스칸디아모스 토피어리(대) 모스 14cm',40000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_09/spec01.PNG',54,to_date('10/12/2019', 'MM/DD/RRRR'),'N','N',95,'Y','Y',2,12);
--행 157
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'피톤치드 가득한 율마 깨지지 않는 화분',18000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_10/spec01.PNG',27,to_date('01/30/2022', 'MM/DD/RRRR'),'N','N',12,'N','N',9,12);
--행 158
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'하트다육 축전 미니화분 공기정화식물 하트선물 반려식물',35000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_11/spec01.PNG',59,to_date('11/04/2020', 'MM/DD/RRRR'),'N','Y',32,'N','Y',6,12);
--행 159
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'미니 올리브나무',32000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_12/spec01.PNG',58,to_date('06/01/2019', 'MM/DD/RRRR'),'N','Y',35,'N','N',7,12);
--행 160
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'보송보송바구니 Pluffy basket -형광핑크',16000,'/resources/image/succulent-plant/succulent-plant/succulent-plant_13/spec01.PNG',37,to_date('11/01/2023', 'MM/DD/RRRR'),'Y','N',46,'N','N',8,12);
--행 161
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'드리핑 다육 식물 화분',8500,'/resources/image/succulent-plant/succulent-plant/succulent-plant_14/spec01.PNG',8,to_date('03/23/2022', 'MM/DD/RRRR'),'Y','N',65,'Y','N',9,12);
--행 162
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'그리너리 스투키 숯화분',21800,'/resources/image/succulent-plant/succulent-plant/succulent-plant_15/spec01.PNG',2,to_date('10/23/2019', 'MM/DD/RRRR'),'N','Y',70,'Y','N',9,12);
--행 163
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'핑크 미니호접',120000,'/resources/image/flower-images/western-orchid_01/comment.PNG',22,to_date('05/11/2019', 'MM/DD/RRRR'),'N','Y',9,'Y','Y',1,8);
--행 164
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'삼색조',120000,'/resources/image/flower-images/western-orchid_02/comment.PNG',97,to_date('09/13/2019', 'MM/DD/RRRR'),'N','N',62,'Y','Y',2,8);
--행 165
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'민천홍',70000,'/resources/image/flower-images/western-orchid_03/comment.PNG',29,to_date('12/28/2020', 'MM/DD/RRRR'),'N','Y',68,'Y','Y',5,8);
--행 166
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'리틀쨈',105000,'/resources/image/flower-images/western-orchid_04/comment.PNG',65,to_date('04/23/2019', 'MM/DD/RRRR'),'Y','Y',54,'N','Y',1,8);
--행 167
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'리틀쨈 유리화기',120000,'/resources/image/flower-images/western-orchid_05/comment.PNG',82,to_date('07/28/2021', 'MM/DD/RRRR'),'N','N',51,'N','Y',7,8);
--행 168
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'사쿠라히메',210000,'/resources/image/flower-images/western-orchid_06/comment.PNG',100,to_date('06/16/2021', 'MM/DD/RRRR'),'N','N',14,'N','Y',8,8);
--행 169
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'만천홍',180000,'/resources/image/flower-images/western-orchid_07/comment.PNG',87,to_date('10/13/2021', 'MM/DD/RRRR'),'N','N',91,'N','Y',1,8);
--행 170
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'발렌티노',190000,'/resources/image/flower-images/western-orchid_08/comment.PNG',84,to_date('09/26/2020', 'MM/DD/RRRR'),'N','N',6,'N','Y',5,8);
--행 171
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'노블화이트 호접란',140000,'/resources/image/flower-images/western-orchid_09/comment.PNG',20,to_date('10/15/2021', 'MM/DD/RRRR'),'N','Y',48,'N','Y',10,8);
--행 172
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'골드 윈드',240000,'/resources/image/flower-images/western-orchid_10/comment.PNG',87,to_date('05/15/2023', 'MM/DD/RRRR'),'N','Y',11,'N','Y',6,8);
--행 173
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'믹스호접란',185000,'/resources/image/flower-images/western-orchid_11/comment.PNG',86,to_date('08/07/2020', 'MM/DD/RRRR'),'Y','N',60,'Y','Y',4,8);
--행 174
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'금의(만천홍, 타이페이골드)',145000,'/resources/image/flower-images/western-orchid_12/comment.PNG',98,to_date('10/19/2020', 'MM/DD/RRRR'),'N','Y',11,'N','Y',2,8);
--행 175
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'포춘',145000,'/resources/image/flower-images/western-orchid_13/comment.PNG',57,to_date('09/07/2021', 'MM/DD/RRRR'),'Y','N',3,'Y','Y',1,8);
--행 176
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'엘레강스',72000,'/resources/image/flower-images/western-orchid_14/comment.PNG',83,to_date('06/01/2022', 'MM/DD/RRRR'),'N','Y',27,'N','Y',7,8);
--행 177
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'포춘 오브제',77000,'/resources/image/flower-images/western-orchid_15/comment.PNG',98,to_date('01/13/2019', 'MM/DD/RRRR'),'Y','N',96,'N','Y',4,8);
--행 178
INSERT INTO TB_PRODUCT (P_ID, P_NAME, P_NETPRICE, P_DETAIL, P_STOCK, P_ENROLL_DATE, P_RETURN_YN, P_TAG_YN, P_SALES, P_DAY_DELIVERY, P_GIFT, SEL_NO, CATEGORY_NO) VALUES (SEQ_PRODUCT.NEXTVAL,'포춘 오브제',77000,'/resources/image/flower-images/western-orchid_15/comment.PNG',98,to_date('01/13/2019', 'MM/DD/RRRR'),'Y','N',96,'N','Y',4,8);
