

-- 삭제 안될 시 전체 삭제 하세용
DROP TABLE "PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "TB_OWNED_COUPON" CASCADE CONSTRAINTS;
DROP TABLE "TB_NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "TB_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "TB_NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "TB_FAQ" CASCADE CONSTRAINTS;
DROP TABLE "TB_BANNER" CASCADE CONSTRAINTS;
DROP TABLE "TB_SELLER" CASCADE CONSTRAINTS;
DROP TABLE "TB_MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "TB_INQUIRY" CASCADE CONSTRAINTS;
DROP TABLE "TB_REVIEW" CASCADE CONSTRAINTS;
DROP TABLE "TB_MEM_INVOICE" CASCADE CONSTRAINTS;
DROP TABLE "TB_ADM_INQ" CASCADE CONSTRAINTS;
DROP TABLE "TB_PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "TB_MEM_PARCEL" CASCADE CONSTRAINTS;
DROP TABLE "TB_NON_MEMBER_ORDER" CASCADE CONSTRAINTS;
DROP TABLE "TB_COUPON" CASCADE CONSTRAINTS;
DROP TABLE "TB_MEM_ORDER" CASCADE CONSTRAINTS;
DROP TABLE "TB_MEM_ORDER_DETAIL" CASCADE CONSTRAINTS;
DROP TABLE "TB_VERIFICATION" CASCADE CONSTRAINTS;
DROP TABLE "TB_SEARCH" CASCADE CONSTRAINTS;
DROP TABLE "TB_INQUIRY_PICTURE" CASCADE CONSTRAINTS;
DROP TABLE "TB_PRODUCT_IMG" CASCADE CONSTRAINTS;
DROP TABLE "TB_1ST_OPTION" CASCADE CONSTRAINTS;
DROP TABLE "TB_DISCOUNT" CASCADE CONSTRAINTS;
DROP TABLE "TB_MEM_CARD" CASCADE CONSTRAINTS;
DROP TABLE "TB_NON_MEMBER_ORDER_DETAIL" CASCADE CONSTRAINTS;
DROP TABLE "TB_CART" CASCADE CONSTRAINTS;
DROP TABLE "TB_MEM_REFUND" CASCADE CONSTRAINTS;
DROP TABLE "TB_NON_REFUND" CASCADE CONSTRAINTS;
DROP TABLE "TB_REVIEW_LIKE" CASCADE CONSTRAINTS;
DROP TABLE "TB_NON_CARD" CASCADE CONSTRAINTS;
DROP TABLE "TB_BOOKMARK" CASCADE CONSTRAINTS;
DROP TABLE "TB_WISHLIST" CASCADE CONSTRAINTS;
DROP TABLE "TB_PRODUCT_REPORT" CASCADE CONSTRAINTS;
DROP TABLE "TB_NON_PARCEL" CASCADE CONSTRAINTS;
DROP TABLE "TB_2ND_OPTION" CASCADE CONSTRAINTS;
DROP TABLE "TABLE1" CASCADE CONSTRAINTS;
------------------------------------------------------------------

----------------------------시퀀스(삭제)----------------------------
DROP SEQUENCE SEQ_NON_PARCEL;
CREATE SEQUENCE SEQ_BANNER;
DROP SEQUENCE SEQ_MEM_PARCEL;
DROP SEQUENCE SEQ_NON_PAYMENT;
DROP SEQUENCE SEQ_MEM_PAYMENT;
DROP SEQUENCE SEQ_MEM_ORDER_DETAIL;
DROP SEQUENCE SEQ_NON_MEMBER_ORDER_DETAIL;
DROP SEQUENCE SEQ_MEM_ORDER;
DROP SEQUENCE SEQ_NON_ORDER;
DROP SEQUENCE SEQ_COUPON;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_ADM_INQ;
DROP SEQUENCE SEQ_2ST_OPTION;
DROP SEQUENCE SEQ_1ST_OPTION;
DROP SEQUENCE SEQ_PRODUCT_REPORT;
DROP SEQUENCE SEQ_INQUIRY;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_VERIFICATION;
DROP SEQUENCE SEQ_REVIEW_COMMENT;
DROP SEQUENCE SEQ_OWNED_COUPON;
------------------------------------------------------------------

----------------------------시퀀스(생성)----------------------------
--배너
CREATE SEQUENCE SEQ_BANNER
NOCACHE;

--회원_주문
CREATE SEQUENCE SEQ_MEM_ORDER
NOCACHE;

--회원_주문_상세
CREATE SEQUENCE SEQ_MEM_ORDER_DETAIL
NOCACHE;

--회원결제
CREATE SEQUENCE SEQ_MEM_PAYMENT
NOCACHE;

--회원_택배
CREATE SEQUENCE SEQ_MEM_PARCEL
NOCACHE;

--비회원_주문
CREATE SEQUENCE SEQ_NON_ORDER
NOCACHE;

--비회원_결제
CREATE SEQUENCE SEQ_NON_PAYMENT
NOCACHE;

--비회원_택배
CREATE SEQUENCE SEQ_NON_PARCEL
NOCACHE;

--비회원_주문_상세
CREATE SEQUENCE SEQ_NON_MEMBER_ORDER_DETAIL
NOCACHE;

--쿠폰번호
CREATE SEQUENCE SEQ_COUPON
NOCACHE;

--상품번호
CREATE SEQUENCE SEQ_PRODUCT
NOCACHE;

--리뷰번호
CREATE SEQUENCE SEQ_REVIEW
NOCACHE;

--관리자문의번호
CREATE SEQUENCE SEQ_ADM_INQ
NOCACHE;

--1차_옵션
CREATE SEQUENCE SEQ_1ST_OPTION
NOCACHE;

--2차_옵션
CREATE SEQUENCE SEQ_2ST_OPTION
NOCACHE;

--상품신고
CREATE SEQUENCE SEQ_PRODUCT_REPORT
NOCACHE;

--문의
CREATE SEQUENCE SEQ_INQUIRY
NOCACHE;

--공지사항
CREATE SEQUENCE SEQ_NOTICE
NOCACHE;

--FAQ
CREATE SEQUENCE SEQ_FAQ
NOCACHE;

--인증키 (임시 시퀀스 없앨꺼)
CREATE SEQUENCE SEQ_VERIFICATION
NOCACHE;

CREATE SEQUENCE SEQ_REVIEW_COMMENT
NOCACHE;
------------------------------------------------------------------

----------------------------테이블(삭제)----------------------------
-- 보유쿠폰
DROP TABLE TB_OWNED_COUPON;
-- 인증키
DROP TABLE TB_VERIFICATION;
-- 공지사항
DROP TABLE TB_NOTICE;
-- 자주하는질문
DROP TABLE TB_FAQ;
-- 배너
DROP TABLE TB_BANNER;
-- 회원_상품_환교반
DROP TABLE TB_MEM_REFUND;
-- 비회원_상품_환교반
DROP TABLE TB_NON_REFUND;
-- 회원_카드쓰기
DROP TABLE TB_MEM_CARD;
-- 비회원_카드쓰기
DROP TABLE TB_NON_CARD;
-- 관리자 문의
DROP TABLE TB_ADM_INQ;
-- 리뷰댓글
DROP TABLE TB_REVIEW_COMMENT;
-- 리뷰좋아요테이블
DROP TABLE TB_REVIEW_LIKE;
-- 판매자 구독 테이블
DROP TABLE TB_BOOKMARK;
-- 최근검색어
DROP TABLE TB_SEARCH;
-- 카트
DROP TABLE TB_CART;
-- 상품신고
DROP TABLE TB_PRODUCT_REPORT;
-- 비회원_택배
DROP TABLE TB_NON_PARCEL;
-- 비회원_송장
DROP TABLE TB_NON_INVOICE;
-- 상품_2차_옵션
DROP TABLE TB_2ND_OPTION;
-- 상품_1차_옵션
DROP TABLE TB_1ST_OPTION;
-- 비회원_결제
DROP TABLE TB_NON_PAYMENT;
-- 위시리스트
DROP TABLE TB_WISHLIST;
-- 비회원_주문
DROP TABLE TB_NON_MEMBER_ORDER;
-- 카테고리
DROP TABLE TB_CATEGORY;
-- 회원 주문
DROP TABLE TB_MEM_ORDER;
-- 회원 주문_상세
DROP TABLE TB_MEM_ORDER_DETAIL;
-- 문의사진
DROP TABLE TB_INQUIRY_PICTURE;
-- 상품사진
DROP TABLE TB_PRODUCT_IMG;
-- 상품할인
DROP TABLE TB_DISCOUNT;
-- 회원_택배
DROP TABLE TB_MEM_PARCEL;
-- 회원송장
DROP TABLE TB_MEM_INVOICE;
-- 회원결제목록
DROP TABLE TB_MEM_PAYMENT;
-- 쿠폰
DROP TABLE TB_COUPON;
-- 비회원_ 주문_상세
DROP TABLE TB_NON_MEMBER_ORDER_DETAIL;
-- 판매
DROP TABLE TB_SELLER;
-- 회원
DROP TABLE TB_MEMBER;
-- 문의
DROP TABLE TB_INQUIRY;
-- 리뷰
DROP TABLE TB_REVIEW;
-- 상품
DROP TABLE TB_PRODUCT;

------------------------------------------------------------------

----------------------------테이블(생성)----------------------------
--카테고리
CREATE TABLE TB_CATEGORY (
	CATEGORY_SMALL	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	CATEGORY_MIDDILE	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	CATEGORY_BIG	VARCHAR2(50)	DEFAULT ''	NOT NULL
);
COMMENT ON COLUMN TB_CATEGORY.CATEGORY_SMALL IS '소카테고리명';
COMMENT ON COLUMN TB_CATEGORY.CATEGORY_MIDDILE IS '중카테고리명';
COMMENT ON COLUMN TB_CATEGORY.CATEGORY_BIG IS '대카테고리명';

--공지사항
CREATE TABLE TB_NOTICE (
	NOTICE_ID	NUMBER	DEFAULT 0	NOT NULL,
	NOTICE_TITLE	VARCHAR2(200)	DEFAULT ''	NOT NULL,
	NOTICE_COMMENT	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	NOTICE_REGDATE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN TB_NOTICE.NOTICE_ID IS '공지사항번호';
COMMENT ON COLUMN TB_NOTICE.NOTICE_TITLE IS '제목';
COMMENT ON COLUMN TB_NOTICE.NOTICE_COMMENT IS '내용';
COMMENT ON COLUMN TB_NOTICE.NOTICE_REGDATE IS '작성일';
--------------------------------------------------------------

-- 자주하는 질문
CREATE TABLE TB_FAQ (
	FAQ_ID	NUMBER	DEFAULT 0	NOT NULL,
	FAQ_CATEGORY	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	FAQ_TITLE	VARCHAR2(200)	DEFAULT ''	NOT NULL,
	FAQ_COMMENT	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	FAQ_REGDATE	DATE	DEFAULT SYSDATE	NOT NULL,
	FAQ_UPDATE	DATE	DEFAULT SYSDATE	NOT NULL
);
COMMENT ON COLUMN TB_FAQ.FAQ_ID IS '질문번호';
COMMENT ON COLUMN TB_FAQ.FAQ_CATEGORY IS '카테고리';
COMMENT ON COLUMN TB_FAQ.FAQ_TITLE IS '제목';
COMMENT ON COLUMN TB_FAQ.FAQ_COMMENT IS '내용';
COMMENT ON COLUMN TB_FAQ.FAQ_REGDATE IS '등록일';
COMMENT ON COLUMN TB_FAQ.FAQ_UPDATE IS '수정일';
------------------------------------------------------------------

--배너
CREATE TABLE TB_BANNER (
	BANNER_ID	NUMBER	DEFAULT 0	NOT NULL,
	BANNER_NAME	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	BANNER_ATTACHEDFILE	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	BANNER_DETAIL	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	BANNER_SHORTCUT	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	BANNER_REGDATE	DATE	DEFAULT ''	NOT NULL,
	BANNER_UPDATE	DATE	DEFAULT SYSDATE	NULL
);
COMMENT ON COLUMN TB_BANNER.BANNER_ID IS '배너번호';
COMMENT ON COLUMN TB_BANNER.BANNER_NAME IS '배너명';
COMMENT ON COLUMN TB_BANNER.BANNER_ATTACHEDFILE IS '첨부파일';
COMMENT ON COLUMN TB_BANNER.BANNER_DETAIL IS '설명';
COMMENT ON COLUMN TB_BANNER.BANNER_SHORTCUT IS '바로가기 링크 주소';
COMMENT ON COLUMN TB_BANNER.BANNER_REGDATE IS '등록일';
COMMENT ON COLUMN TB_BANNER.BANNER_UPDATE IS '수정일';
--------------------------------------------------------------

-- 판매자
CREATE TABLE TB_SELLER (
	SEL_ID	VARCHAR2(30)	DEFAULT ''	NOT NULL,
	SEL_PW	VARCHAR2(30)	DEFAULT ''	NOT NULL,
	SEL_BUSINESS_NO	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	SEL_STORE_NAME	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	SEL_NAME	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	SEL_EMAIL	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	SEL_PHONE	VARCHAR2(30)	DEFAULT ''	NOT NULL,
	SEL_TEL	VARCHAR2(30)	DEFAULT ''	NULL,
	SEL_FAX	VARCHAR2(50)	DEFAULT ''	NULL,
	SEL_POSTAL	NUMBER	DEFAULT 0	NULL,
	SEL_STREET	VARCHAR2(200)	DEFAULT ''	NULL,
	SEL_ADDRESS	VARCHAR2(200)	DEFAULT ''	NULL,
	SEL_IMG	VARCHAR2(200)	DEFAULT ''	NULL
);
COMMENT ON COLUMN TB_SELLER.SEL_ID IS '판매자ID';
COMMENT ON COLUMN TB_SELLER.SEL_PW IS '비밀번호';
COMMENT ON COLUMN TB_SELLER.SEL_BUSINESS_NO IS '사업자번호';
COMMENT ON COLUMN TB_SELLER.SEL_STORE_NAME IS '업체명';
COMMENT ON COLUMN TB_SELLER.SEL_NAME IS '대표자명';
COMMENT ON COLUMN TB_SELLER.SEL_EMAIL IS 'EMAIL';
COMMENT ON COLUMN TB_SELLER.SEL_PHONE IS '휴대폰';
COMMENT ON COLUMN TB_SELLER.SEL_TEL IS '전화번호';
COMMENT ON COLUMN TB_SELLER.SEL_FAX IS '팩스번호';
COMMENT ON COLUMN TB_SELLER.SEL_POSTAL IS '사업장주소1(우편번호)';
COMMENT ON COLUMN TB_SELLER.SEL_STREET IS '사업장주소2(주소)';
COMMENT ON COLUMN TB_SELLER.SEL_ADDRESS IS '사업장주소3(상세주소)';
COMMENT ON COLUMN TB_SELLER.SEL_IMG IS '프로필사진경로';
------------------------------------------------------------------

-- 회원
CREATE TABLE TB_MEMBER (
	MEM_ID	VARCHAR2(30)	DEFAULT ''	NOT NULL,
	MEM_PW	VARCHAR2(30)	DEFAULT ''	NOT NULL,
	MEM_EMAIL	VARCHAR2(40)	DEFAULT ''	NOT NULL,
	MEM_NAME	VARCHAR2(20)	DEFAULT ''	NOT NULL,
	MEM_PHONE	VARCHAR2(20)	DEFAULT ''	NOT NULL,
	MEM_POSTAL	NUMBER	DEFAULT 0	NOT NULL,
	MEM_STREET	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	MEM_ADDRESS	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	MEM_ENROLL_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	MEM_MILEAGE	NUMBER	DEFAULT 0	NULL,
	MEM_IMG	VARCHAR2(200)	DEFAULT ''	NULL,
	MEM_GET_PHONE	CHAR(3)	DEFAULT 'N'	NOT NULL,
	MEM_BIRTHDATE	DATE	DEFAULT ''	NOT NULL,
	MEM_GENDER	NUMBER	DEFAULT 0	NOT NULL,
	MEM_STATUS	CHAR(3)	DEFAULT 'N'	NOT NULL
);
COMMENT ON COLUMN TB_MEMBER.MEM_ID IS '개인회원ID';
COMMENT ON COLUMN TB_MEMBER.MEM_PW IS '비밀번호';
COMMENT ON COLUMN TB_MEMBER.MEM_EMAIL IS '이메일';
COMMENT ON COLUMN TB_MEMBER.MEM_NAME IS '회원이름';
COMMENT ON COLUMN TB_MEMBER.MEM_PHONE IS '휴대폰번호';
COMMENT ON COLUMN TB_MEMBER.MEM_POSTAL IS '회원주소1(우편번호)';
COMMENT ON COLUMN TB_MEMBER.MEM_STREET IS '회원주소2(주소)';
COMMENT ON COLUMN TB_MEMBER.MEM_ADDRESS IS '회원주소3(상세주소)';
COMMENT ON COLUMN TB_MEMBER.MEM_ENROLL_DATE IS '가입일';
COMMENT ON COLUMN TB_MEMBER.MEM_MILEAGE IS '마일리지';
COMMENT ON COLUMN TB_MEMBER.MEM_IMG IS '프로필이미지경로';
COMMENT ON COLUMN TB_MEMBER.MEM_GET_PHONE IS 'Y/N';
COMMENT ON COLUMN TB_MEMBER.MEM_BIRTHDATE IS '생년월일';
COMMENT ON COLUMN TB_MEMBER.MEM_GENDER IS '1. 남자 2. 여자';
COMMENT ON COLUMN TB_MEMBER.MEM_STATUS IS 'Y/N';
------------------------------------------------------------------

-- 문의
CREATE TABLE TB_INQUIRY (
	INQUIRY_ID	NUMBER	DEFAULT ''	NOT NULL,
	INQUIRY_TYPE	NUMBER	DEFAULT 5	NOT NULL CHECK(INQUIRY_TYPE IN(1,2,3,4,5)),
	INQUIRY_TITLE	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	INQUIRY_COMMENT	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	P_ID	VARCHAR2(20)	DEFAULT ''	NOT NULL,
	MEM_ID	VARCHAR2(30)	DEFAULT ''	NOT NULL
);
COMMENT ON COLUMN TB_INQUIRY.INQUIRY_ID IS '문의번호';
COMMENT ON COLUMN TB_INQUIRY.INQUIRY_TYPE IS '1.상품/2.교환/3.반품/4.환불/5.기타';
COMMENT ON COLUMN TB_INQUIRY.INQUIRY_TITLE IS '제목';
COMMENT ON COLUMN TB_INQUIRY.INQUIRY_COMMENT IS '내용';
COMMENT ON COLUMN TB_INQUIRY.P_ID IS '상품번호';
COMMENT ON COLUMN TB_INQUIRY.MEM_ID IS '개인회원ID';
------------------------------------------------------------------

--리뷰
CREATE TABLE TB_REVIEW (
	REVIEW_ID	NUMBER	DEFAULT 0	NOT NULL,
	P_ID	NUMBER	DEFAULT 0	NOT NULL,
	REVIEW_RATING	NUMBER	DEFAULT -1	NOT NULL,
	REVIEW_DETAIL	VARCHAR2(4000)	DEFAULT ''	NULL,
	REVIEW_IMG	VARCHAR2(4000)	DEFAULT ''	NULL,
	REVIEW_REPLY	VARCHAR2(4000)	DEFAULT ''	NULL,
	REVIEW_ADD_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	OD_ID	NUMBER	DEFAULT 0	NOT NULL
);
COMMENT ON COLUMN TB_REVIEW.REVIEW_ID IS '리뷰번호';
COMMENT ON COLUMN TB_REVIEW.P_ID IS '상품번호';
COMMENT ON COLUMN TB_REVIEW.REVIEW_RATING IS '평점 :최고 5점';
COMMENT ON COLUMN TB_REVIEW.REVIEW_DETAIL IS '리뷰내용';
COMMENT ON COLUMN TB_REVIEW.REVIEW_IMG IS '리뷰사진';
COMMENT ON COLUMN TB_REVIEW.REVIEW_REPLY IS '리뷰댓글';
COMMENT ON COLUMN TB_REVIEW.REVIEW_ADD_DATE IS '작성일';
COMMENT ON COLUMN TB_REVIEW.OD_ID IS '주문상세번호';
------------------------------------------------------------------

--리뷰댓글
CREATE TABLE TB_REVIEW_COMMENT(
    COMMENT_NO NUMBER DEFAULT 0 NOT NULL,
    COMMENT_MESSAGE VARCHAR2(4000) DEFAULT '' NOT NULL,
    COMMENT_DATE DATE DEFAULT SYSDATE NOT NULL,
    REVIEW_ID NUMBER DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN TB_REVIEW_COMMENT.COMMENT_NO IS '리뷰댓글번호';
COMMENT ON COLUMN TB_REVIEW_COMMENT.COMMENT_MESSAGE IS '리뷰댓글';
COMMENT ON COLUMN TB_REVIEW_COMMENT.COMMENT_DATE IS '작성일';
COMMENT ON COLUMN TB_REVIEW_COMMENT.REVIEW_ID IS '리뷰번호';

------------------------------------------------------------------

--회원 송장관리
CREATE TABLE TB_MEM_INVOICE (
	INVOICE_ID	NUMBER	DEFAULT 0	NOT NULL,
	PAY_STATUS	CHAR(1)	DEFAULT 'N'	NULL,
	INVOICE_REGDATE	DATE	DEFAULT SYSDATE	NULL,
	PAY_ID	NUMBER	DEFAULT 0	NOT NULL,
	OD_ID	NUMBER	DEFAULT 0	NOT NULL
);
COMMENT ON COLUMN TB_MEM_INVOICE.INVOICE_ID IS '송장번호';
COMMENT ON COLUMN TB_MEM_INVOICE.PAY_STATUS IS 'Y/N';
COMMENT ON COLUMN TB_MEM_INVOICE.INVOICE_REGDATE IS '송장등록일';
COMMENT ON COLUMN TB_MEM_INVOICE.PAY_ID IS '결제번호';
COMMENT ON COLUMN TB_MEM_INVOICE.OD_ID IS '주문상세번호';
------------------------------------------------------------------

-- 관리자문의
CREATE TABLE TB_ADM_INQ (
	ADM_INQ_NUMBER	NUMBER	DEFAULT 0	NOT NULL,
	ADM_INQ_TYPE	NUMBER	DEFAULT 3	NOT NULL CHECK(ADM_INQ_TYPE IN(1,2,3)),
	ADM_INQ_TITLE	VARCHAR2(100)	DEFAULT ''	NULL,
	ADM_INQ_DETAIL	VARCHAR2(4000)	DEFAULT ''	NULL,
	ADM_INQ_ADD_DATE	DATE	DEFAULT SYSDATE	NULL,
	ADM_INQ_STATUS_YN	VARCHAR2(3)	DEFAULT 'N'	NULL,
	SEL_ID	VARCHAR2(30)	DEFAULT ''	NOT NULL
);
COMMENT ON COLUMN TB_ADM_INQ.ADM_INQ_NUMBER IS '관리자문의번호';
COMMENT ON COLUMN TB_ADM_INQ.ADM_INQ_TYPE IS '1 : 리뷰삭제/ 2: 상품등록/ 3: 기타';
COMMENT ON COLUMN TB_ADM_INQ.ADM_INQ_TITLE IS '제목';
COMMENT ON COLUMN TB_ADM_INQ.ADM_INQ_DETAIL IS '내용';
COMMENT ON COLUMN TB_ADM_INQ.ADM_INQ_ADD_DATE IS '등록일';
COMMENT ON COLUMN TB_ADM_INQ.ADM_INQ_STATUS_YN IS 'Y/N';
COMMENT ON COLUMN TB_ADM_INQ.SEL_ID IS '판매자ID';
------------------------------------------------------------------

-- 상품
CREATE TABLE TB_PRODUCT (
	P_ID	NUMBER	DEFAULT 0	NOT NULL,
	P_NAME	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	P_NETPRICE	NUMBER	DEFAULT 0	NOT NULL,
	P_DETAIL	VARCHAR2(4000)	DEFAULT ''	NULL,
	P_STOCK	NUMBER	DEFAULT 0	NULL,
	P_ENROLL_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	P_RETURN_YN	CHAR(3)	DEFAULT 'N'	NULL,
	P_TAG_YN	CHAR(3)	DEFAULT 'N'	NULL,
	SAL_ID	VARCHAR2(12)	DEFAULT ''	NOT NULL,
	CATEGORY_SMALL	VARCHAR2(50)	DEFAULT ''	NOT NULL
);
COMMENT ON COLUMN TB_PRODUCT.P_ID IS '상품번호';
COMMENT ON COLUMN TB_PRODUCT.P_NAME IS '상품명';
COMMENT ON COLUMN TB_PRODUCT.P_NETPRICE IS '가격';
COMMENT ON COLUMN TB_PRODUCT.P_DETAIL IS '상세설명';
COMMENT ON COLUMN TB_PRODUCT.P_STOCK IS '총수량';
COMMENT ON COLUMN TB_PRODUCT.P_ENROLL_DATE IS '등록일';
COMMENT ON COLUMN TB_PRODUCT.P_RETURN_YN IS '환불여부(Y,N)';
COMMENT ON COLUMN TB_PRODUCT.P_TAG_YN IS '카드여부(Y,N)';
COMMENT ON COLUMN TB_PRODUCT.SAL_ID IS '판매자ID';
COMMENT ON COLUMN TB_PRODUCT.CATEGORY_SMALL IS '소카테고리명';
------------------------------------------------------------------

--회원 택배
CREATE TABLE TB_MEM_PARCEL (
	PARCEL_ID	NUMBER	DEFAULT 0	NOT NULL,
	PARCEL_NAME	VARCHAR2(50)	DEFAULT ''	NULL,
	PARCEL_STATUS	CHAR(1)	DEFAULT 'N'	NULL,
	COL_DATE	DATE	DEFAULT SYSDATE	NULL,
	INVOICE_ID	NUMBER	DEFAULT 0	NOT NULL
);
COMMENT ON COLUMN TB_MEM_PARCEL.PARCEL_ID IS '택배번호';
COMMENT ON COLUMN TB_MEM_PARCEL.PARCEL_NAME IS '택배사이름';
COMMENT ON COLUMN TB_MEM_PARCEL.PARCEL_STATUS IS 'Y/N';
COMMENT ON COLUMN TB_MEM_PARCEL.COL_DATE IS '택배수거일';
COMMENT ON COLUMN TB_MEM_PARCEL.INVOICE_ID IS '송장번호';
------------------------------------------------------------------

-- 비회원_주문
CREATE TABLE TB_NON_MEMBER_ORDER (
	ORD_ID	NUMBER	DEFAULT 0	NOT NULL,
	ORD_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	ORD_POSTAL	NUMBER	DEFAULT ''	NOT NULL,
	ORD_STREET	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	ORD_ADDRESS	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	ORD_REQUEST	VARCHAR2(500)	DEFAULT ''	NULL,
	ORD_RECEIVER_NAME	CHAR(20)	DEFAULT ''	NOT NULL,
	ORD_RECEIVER_PHONE	VARCHAR2(20)	DEFAULT ''	NOT NULL
);
COMMENT ON COLUMN TB_NON_MEMBER_ORDER.ORD_ID IS '주문번호';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER.ORD_DATE IS '주문날짜';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER.ORD_POSTAL IS '배송지주소1(우편번호)';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER.ORD_STREET IS '배송지주소2(주소)';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER.ORD_ADDRESS IS '배송지주소3(상세주소)';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER.ORD_REQUEST IS '배송요청사항';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER.ORD_RECEIVER_NAME IS '수령자이름';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER.ORD_RECEIVER_PHONE IS '수령자전화번호';
------------------------------------------------------------------

--쿠폰
CREATE TABLE TB_COUPON (
	COU_ID	NUMBER	DEFAULT 0	NOT NULL,
	COU_NAME	VARCHAR2(255)	DEFAULT ''	NULL,
	COU_DETAIL	VARCHAR2(255)	DEFAULT ''	NULL,
	COU_IMG	VARCHAR2(255)	DEFAULT ''	NULL,
	COU_EXPIRE	DATE	DEFAULT SYSDATE+7	NULL,
	COU_CONDITION_1	VARCHAR2(255)	DEFAULT ''	NULL,
    COU_CONDITION_2	VARCHAR2(255)	DEFAULT ''	NULL,
	COU_CONDITION_3	VARCHAR2(255)	DEFAULT ''	NULL,
	COU_REGDATE	DATE	DEFAULT SYSDATE	NULL,
	COU_EDIT_DATE	DATE	DEFAULT SYSDATE	NULL,
    COU_DISCOUNT    NUMBER  DEFAULT 0   NOT NULL
);
COMMENT ON COLUMN TB_COUPON.COU_ID IS '쿠폰번호';
COMMENT ON COLUMN TB_COUPON.COU_NAME IS '쿠폰명';
COMMENT ON COLUMN TB_COUPON.COU_DETAIL IS '내용';
COMMENT ON COLUMN TB_COUPON.COU_IMG IS '썸네일 경로';
COMMENT ON COLUMN TB_COUPON.COU_EXPIRE IS '만료일';
COMMENT ON COLUMN TB_COUPON.COU_CONDITION_1 IS '조건1';
COMMENT ON COLUMN TB_COUPON.COU_CONDITION_2 IS '조건2';
COMMENT ON COLUMN TB_COUPON.COU_CONDITION_3 IS '조건3';
COMMENT ON COLUMN TB_COUPON.COU_REGDATE IS '등록일';
COMMENT ON COLUMN TB_COUPON.COU_EDIT_DATE IS '수정일';
COMMENT ON COLUMN TB_COUPON.COU_DISCOUNT IS '0< :  지급액 / 0> : 할인 백분율';
------------------------------------------------------------------

-- 회원_주문
CREATE TABLE TB_MEM_ORDER (
	ORD_ID	NUMBER	DEFAULT 0	NOT NULL,
	MEM_ID	VARCHAR2(12)	DEFAULT ''	NOT NULL,
	ORD_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	ORD_POSTAL	NUMBER	DEFAULT 0	NOT NULL,
	ORD_STREET	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	ORD_ADDRESS	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	ORD_RECIEVER_NAME	CHAR(20)	DEFAULT ''	NOT NULL,
	ORD_RECIEVER_PHONE	VARCHAR2(20)	DEFAULT ''	NOT NULL,
	ORD_REQUEST	VARCHAR2(500)	DEFAULT ''	NULL
);
COMMENT ON COLUMN TB_MEM_ORDER.ORD_ID IS '주문번호';
COMMENT ON COLUMN TB_MEM_ORDER.MEM_ID IS '개인회원ID';
COMMENT ON COLUMN TB_MEM_ORDER.ORD_DATE IS '주문날짜';
COMMENT ON COLUMN TB_MEM_ORDER.ORD_POSTAL IS '수령자주소1(우편번호)';
COMMENT ON COLUMN TB_MEM_ORDER.ORD_STREET IS '수령자주소2(주소)';
COMMENT ON COLUMN TB_MEM_ORDER.ORD_ADDRESS IS '수령자주소3(상세주소)';
COMMENT ON COLUMN TB_MEM_ORDER.ORD_RECIEVER_NAME IS '수령자이름';
COMMENT ON COLUMN TB_MEM_ORDER.ORD_RECIEVER_PHONE IS '수령자전화번호';
COMMENT ON COLUMN TB_MEM_ORDER.ORD_REQUEST IS '배송요청사항';
------------------------------------------------------------------

--회원_주문_상세
CREATE TABLE TB_MEM_ORDER_DETAIL (
	OD_ID	NUMBER	DEFAULT 0	NOT NULL,
	OD_COUNT	NUMBER	DEFAULT 0	NULL,
	OD_STATUS	NUMBER	DEFAULT 1	NULL CHECK(OD_STATUS IN(1,2,3)),
	ORD_ID	NUMBER	DEFAULT 0	NOT NULL,
	P_ID	NUMBER	DEFAULT 0	NOT NULL,
	MEM_ID	VARCHAR2(12)	DEFAULT ''	NOT NULL
);
COMMENT ON COLUMN TB_MEM_ORDER_DETAIL.OD_ID IS '주문상세번호';
COMMENT ON COLUMN TB_MEM_ORDER_DETAIL.OD_COUNT IS '상품수량';
COMMENT ON COLUMN TB_MEM_ORDER_DETAIL.OD_STATUS IS '1.준비/2.배송중/3.완료';
COMMENT ON COLUMN TB_MEM_ORDER_DETAIL.ORD_ID IS '주문번호';
COMMENT ON COLUMN TB_MEM_ORDER_DETAIL.P_ID IS '상품번호';
COMMENT ON COLUMN TB_MEM_ORDER_DETAIL.MEM_ID IS '개인회원ID';
------------------------------------------------------------------

--보유쿠폰
CREATE TABLE TB_OWNED_COUPON (
	MEM_ID	VARCHAR2(12)	DEFAULT ''	NOT NULL,
	COU_ID	NUMBER	DEFAULT 0	NOT NULL,
	COU_USED_YN	CHAR(3)	DEFAULT 'N'	NULL
);
COMMENT ON COLUMN TB_OWNED_COUPON.MEM_ID IS '개인회원ID';
COMMENT ON COLUMN TB_OWNED_COUPON.COU_ID IS '쿠폰번호';
COMMENT ON COLUMN TB_OWNED_COUPON.COU_USED_YN IS 'Y/N';
------------------------------------------------------------------

--인증키
CREATE TABLE TB_VERIFICATION (
	VERIF_ID	VARCHAR2(30)	DEFAULT 0	NOT NULL,
	MEM_ID	VARCHAR2(30)	DEFAULT 0	NOT NULL,
	VERIF_EMAIL	VARCHAR2(30)	DEFAULT ''	NOT NULL,
	VERIF_TYPE	NUMBER	DEFAULT 0	NOT NULL CHECK(VERIF_TYPE IN (0,1,2,3,4)),
	VERIF_CREATE_DATE	DATE	DEFAULT SYSDATE	NULL,
	VERIF_USED_DATE	DATE	DEFAULT SYSDATE	NULL,
	VERIF_DEL_YN	CHAR(1)	DEFAULT 'N'	NOT NULL
);
COMMENT ON COLUMN TB_VERIFICATION.VERIF_ID IS 'PK';
COMMENT ON COLUMN TB_VERIFICATION.MEM_ID IS '이메일 인증이 필요한 회원 PK';
COMMENT ON COLUMN TB_VERIFICATION.VERIF_EMAIL IS '이메일 인증키';
COMMENT ON COLUMN TB_VERIFICATION.VERIF_TYPE IS '인증종류 1: 회원가입, 2:이메일변경, 3.아이디 분실, 4. 패스워드 분실0:ERR';
COMMENT ON COLUMN TB_VERIFICATION.VERIF_CREATE_DATE IS '인증키 생성 일자';
COMMENT ON COLUMN TB_VERIFICATION.VERIF_USED_DATE IS '인증키 사용 일자';
COMMENT ON COLUMN TB_VERIFICATION.VERIF_DEL_YN IS 'Y/N';
------------------------------------------------------------------

--검색키워드
CREATE TABLE TB_SEARCH (
	MEM_ID	VARCHAR2(20)	DEFAULT ''	NOT NULL,
	SEARCH_KEYWORD	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	SEARCH_DATE	DATE	DEFAULT SYSDATE	NOT NULL
);
COMMENT ON COLUMN TB_SEARCH.MEM_ID IS '개인회원ID';
COMMENT ON COLUMN TB_SEARCH.SEARCH_KEYWORD IS '키워드';
COMMENT ON COLUMN TB_SEARCH.SEARCH_DATE IS '일시';
------------------------------------------------------------------

--문의사진
CREATE TABLE TB_INQUIRY_PICTURE (
	INQUIRY_PICTURE_ID	NUMBER	DEFAULT 0	NOT NULL,
	INQUIRY_PICTURE_IMG	VARCHAR2(4000)	DEFAULT ''	NOT NULL
);
COMMENT ON COLUMN TB_INQUIRY_PICTURE.INQUIRY_PICTURE_ID IS '문의번호';
COMMENT ON COLUMN TB_INQUIRY_PICTURE.INQUIRY_PICTURE_IMG IS '문의사진경로';
------------------------------------------------------------------

--상품사진
CREATE TABLE TB_PRODUCT_IMG (
	P_ID	NUMBER	DEFAULT 0	NOT NULL,
	P_IMG1	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	P_IMG2	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	P_IMG3	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	P_IMG4	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	P_IMG5	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	P_IMG6	VARCHAR2(4000)	DEFAULT ''	NULL,
	P_IMG7	VARCHAR2(4000)	DEFAULT ''	NULL,
	P_IMG8	VARCHAR2(4000)	DEFAULT ''	NULL,
	P_IMG9	VARCHAR2(4000)	DEFAULT ''	NULL,
	P_IMG10	VARCHAR2(4000)	DEFAULT ''	NULL
);
COMMENT ON COLUMN TB_PRODUCT_IMG.P_ID IS '상품번호';
COMMENT ON COLUMN TB_PRODUCT_IMG.P_IMG1 IS '이미지경로1';
COMMENT ON COLUMN TB_PRODUCT_IMG.P_IMG2 IS '이미지경로2';
COMMENT ON COLUMN TB_PRODUCT_IMG.P_IMG3 IS '이미지경로3';
COMMENT ON COLUMN TB_PRODUCT_IMG.P_IMG4 IS '이미지경로4';
COMMENT ON COLUMN TB_PRODUCT_IMG.P_IMG5 IS '이미지경로5';
COMMENT ON COLUMN TB_PRODUCT_IMG.P_IMG6 IS '이미지경로6';
COMMENT ON COLUMN TB_PRODUCT_IMG.P_IMG7 IS '이미지경로7';
COMMENT ON COLUMN TB_PRODUCT_IMG.P_IMG8 IS '이미지경로8';
COMMENT ON COLUMN TB_PRODUCT_IMG.P_IMG9 IS '이미지경로9';
COMMENT ON COLUMN TB_PRODUCT_IMG.P_IMG10 IS '이미지경로10';
------------------------------------------------------------------

--상품_1차옵션
CREATE TABLE TB_1ST_OPTION (
	OPTION_ID	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	OPTION_MAIN	VARCHAR2(1000)	DEFAULT ''	NOT NULL,
	OPTION_PRICE	NUMBER	DEFAULT 0	NOT NULL,
	OPTION_STOCK	NUMBER	DEFAULT 0	NULL,
	P_ID	VARCHAR2(20)	DEFAULT 0	NOT NULL
);
COMMENT ON COLUMN TB_1ST_OPTION.OPTION_ID IS '옵션아이디';
COMMENT ON COLUMN TB_1ST_OPTION.OPTION_MAIN IS '내용';
COMMENT ON COLUMN TB_1ST_OPTION.OPTION_PRICE IS '가격';
COMMENT ON COLUMN TB_1ST_OPTION.OPTION_STOCK IS '재고';
COMMENT ON COLUMN TB_1ST_OPTION.P_ID IS '상품번호';
------------------------------------------------------------------

--상품할인
CREATE TABLE TB_DISCOUNT (
	P_ID	NUMBER	DEFAULT 0	NOT NULL,
	DISCOUNT_RATE	NUMBER	DEFAULT 0	NULL
);
COMMENT ON COLUMN TB_DISCOUNT.P_ID IS '상품번호';
COMMENT ON COLUMN TB_DISCOUNT.DISCOUNT_RATE IS '할인율';
------------------------------------------------------------------

--회원카드쓰기
CREATE TABLE TB_MEM_CARD (
	OD_ID	NUMBER	DEFAULT 0	NOT NULL,
	RIBBON_LEFT	VARCHAR2(4000)	DEFAULT ''	NULL,
	RIBBON_RIGHT	VARCHAR2(4000)	DEFAULT ''	NULL,
	RIBBON_COMMENT	VARCHAR2(4000)	DEFAULT ''	NULL
);
COMMENT ON COLUMN TB_MEM_CARD.OD_ID IS '주문상세번호';
COMMENT ON COLUMN TB_MEM_CARD.RIBBON_LEFT IS '리본좌측';
COMMENT ON COLUMN TB_MEM_CARD.RIBBON_RIGHT IS '리본우측';
COMMENT ON COLUMN TB_MEM_CARD.RIBBON_COMMENT IS '메세지';
------------------------------------------------------------------

--비회원_주문_상세
CREATE TABLE TB_NON_MEMBER_ORDER_DETAIL (
	OD_ID	NUMBER	DEFAULT 0	NOT NULL,
	OD_COUNT	NUMBER	DEFAULT 0	NOT NULL,
	OD_STATUS	NUMBER	DEFAULT 1	NOT NULL CHECK(OD_STATUS IN(1,2,3)),
	P_ID	VARCHAR2(20)	DEFAULT ''	NOT NULL,
	ORD_ID	NUMBER	DEFAULT 0	NOT NULL
);
COMMENT ON COLUMN TB_NON_MEMBER_ORDER_DETAIL.OD_ID IS '주문상세정보';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER_DETAIL.OD_COUNT IS '상품수량';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER_DETAIL.OD_STATUS IS '1.준비중/2.배송중/3.배송완료';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER_DETAIL.P_ID IS '상품번호';
COMMENT ON COLUMN TB_NON_MEMBER_ORDER_DETAIL.ORD_ID IS '주문번호';
------------------------------------------------------------------

--장바구니
CREATE TABLE TB_CART (
	MEM_ID	VARCHAR2(30)	DEFAULT ''	NOT NULL,
	P_ID	NUMBER	DEFAULT 0	NOT NULL,
	CART_STOCK	NUMBER	DEFAULT 0	NOT NULL,
	CART_ADD_DATE	DATE	DEFAULT SYSDATE	NOT NULL
);
COMMENT ON COLUMN TB_CART.MEM_ID IS '개인회원ID';
COMMENT ON COLUMN TB_CART.P_ID IS '상품번호';
COMMENT ON COLUMN TB_CART.CART_STOCK IS '수량';
COMMENT ON COLUMN TB_CART.CART_ADD_DATE IS '등록일';
------------------------------------------------------------------

--회원_상품_환교반
CREATE TABLE TB_MEM_REFUND (
	OD_ID	NUMBER	DEFAULT 0	NOT NULL,
	REFUND_TYPE	NUMBER	DEFAULT 0	NOT NULL CHECK(REFUND_TYPE IN(0,1,2,3)),
	REFUND_TITLE	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	REFUND_COMMENT	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	REFUND_IMG	VARCHAR2(4000)	DEFAULT ''	NULL,
	REFUND_APPROVAL_STATUS	NUMBER	DEFAULT 1	NULL CHECK(REFUND_APPROVAL_STATUS IN(1,2,3)),
	REFUND_STATUS	NUMBER	DEFAULT 1 NOT NULL CHECK(REFUND_STATUS IN(1,2,3))	
);
COMMENT ON COLUMN TB_MEM_REFUND.OD_ID IS '주문상세번호';
COMMENT ON COLUMN TB_MEM_REFUND.REFUND_TYPE IS '1.교환/2.환불/3.반품';
COMMENT ON COLUMN TB_MEM_REFUND.REFUND_TITLE IS '제목';
COMMENT ON COLUMN TB_MEM_REFUND.REFUND_COMMENT IS '내용';
COMMENT ON COLUMN TB_MEM_REFUND.REFUND_IMG IS '사진경로';
COMMENT ON COLUMN TB_MEM_REFUND.REFUND_APPROVAL_STATUS IS '1.승인대기/2.승인됨/3.승인거절';
COMMENT ON COLUMN TB_MEM_REFUND.REFUND_STATUS IS '1.접수/2.처리중/3.처리완료';
------------------------------------------------------------------

--비회원_상품_환교반
CREATE TABLE TB_NON_REFUND (
	OD_ID	NUMBER	DEFAULT 0	NOT NULL,
	REFUND_TYPE	NUMBER	DEFAULT ''	NOT NULL CHECK(REFUND_TYPE IN(0,1,2,3)),
	REFUND_TITLE	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	REFUND_COMMENT	VARCHAR2(4000)	DEFAULT ''	NOT NULL,
	REFUND_PHONE	VARCHAR2(13)	DEFAULT ''	NOT NULL,
	REFUND_EMAIL	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	REFUND_IMG	VARCHAR2(4000)	DEFAULT ''	NULL,
	REFUND_APPROVAL_STATUS	NUMBER	DEFAULT 1	NULL CHECK(REFUND_APPROVAL_STATUS IN(1,2,3)),
	REFUND_STATUS	NUMBER	DEFAULT 1	NOT NULL CHECK(REFUND_STATUS IN(1,2,3))
);
COMMENT ON COLUMN TB_NON_REFUND.OD_ID IS '주문상세정보';
COMMENT ON COLUMN TB_NON_REFUND.REFUND_TYPE IS '1.교환/2.환불/3.반품';
COMMENT ON COLUMN TB_NON_REFUND.REFUND_TITLE IS '제목';
COMMENT ON COLUMN TB_NON_REFUND.REFUND_COMMENT IS '내용';
COMMENT ON COLUMN TB_NON_REFUND.REFUND_PHONE IS '전화번호';
COMMENT ON COLUMN TB_NON_REFUND.REFUND_EMAIL IS '이메일';
COMMENT ON COLUMN TB_NON_REFUND.REFUND_IMG IS '사진경로';
COMMENT ON COLUMN TB_NON_REFUND.REFUND_APPROVAL_STATUS IS '1.승인됨/2.승인거절/3.승인중';
COMMENT ON COLUMN TB_NON_REFUND.REFUND_STATUS IS '접수/처리중/처리완료';
------------------------------------------------------------------

--회원결제목록
CREATE TABLE TB_MEM_PAYMENT (
	PAY_ID	NUMBER	DEFAULT 0	NOT NULL,
	OD_ID	NUMBER	DEFAULT 0	NOT NULL,
	TOTAL_PAY	NUMBER	DEFAULT 0	NULL,
	PAY_DATE	DATE	DEFAULT SYSDATE	NULL
);
COMMENT ON COLUMN TB_MEM_PAYMENT.PAY_ID IS '결제번호';
COMMENT ON COLUMN TB_MEM_PAYMENT.OD_ID IS '주문상세번호';
COMMENT ON COLUMN TB_MEM_PAYMENT.TOTAL_PAY IS '총결제금액';
COMMENT ON COLUMN TB_MEM_PAYMENT.PAY_DATE IS '결제일';

--리뷰추천
CREATE TABLE TB_REVIEW_LIKE (
	MEM_ID	VARCHAR2(30)	DEFAULT ''	NOT NULL,
	REVIEW_ID	NUMBER	DEFAULT 0	NOT NULL,
	LIKE_DATE	DATE	DEFAULT SYSDATE	NOT NULL
);
COMMENT ON COLUMN TB_REVIEW_LIKE.MEM_ID IS '개인회원ID';
COMMENT ON COLUMN TB_REVIEW_LIKE.REVIEW_ID IS '리뷰번호';
COMMENT ON COLUMN TB_REVIEW_LIKE.LIKE_DATE IS '추천일자';
------------------------------------------------------------------

--비회원_카드쓰기
CREATE TABLE TB_NON_CARD (
	OD_ID	NUMBER	DEFAULT 0	NOT NULL,
	RIBBON_LEFT	VARCHAR2(4000)	DEFAULT ''	NULL,
	RIBBON_RIGHT	VARCHAR2(4000)	DEFAULT ''	NULL,
	RIBBON_MESSAGE	VARCHAR2(4000)	DEFAULT ''	NULL
);
COMMENT ON COLUMN TB_NON_CARD.OD_ID IS '주문상세정보';
COMMENT ON COLUMN TB_NON_CARD.RIBBON_LEFT IS '리본좌측메세지';
COMMENT ON COLUMN TB_NON_CARD.RIBBON_RIGHT IS '리본우측메세지';
COMMENT ON COLUMN TB_NON_CARD.RIBBON_MESSAGE IS '카드메세지';
------------------------------------------------------------------

--판매자_구독
CREATE TABLE TB_BOOKMARK (
	MEM_ID	VARCHAR2(12)	DEFAULT ''	NOT NULL,
	SEL_ID	VARCHAR(20)	DEFAULT ''	NOT NULL
);
COMMENT ON COLUMN TB_BOOKMARK.MEM_ID IS '개인회원ID';
COMMENT ON COLUMN TB_BOOKMARK.SEL_ID IS '판매자ID';
------------------------------------------------------------------

--위시리스트
CREATE TABLE TB_WISHLIST (
	MEM_ID	VARCHAR2(12)	DEFAULT ''	NOT NULL,
	P_ID	NUMBER	DEFAULT 0	NOT NULL,
	WISHLIST_DATE	DATE	DEFAULT SYSDATE	NOT NULL
);
COMMENT ON COLUMN TB_WISHLIST.MEM_ID IS '개인회원ID';
COMMENT ON COLUMN TB_WISHLIST.P_ID IS '상품번호';
COMMENT ON COLUMN TB_WISHLIST.WISHLIST_DATE IS '찜날짜';

--상품신고
CREATE TABLE TB_PRODUCT_REPORT (
	REPORT_ID	NUMBER	DEFAULT ''	NOT NULL,
	REPORT_CATEGORY	NUMBER	DEFAULT 1	NOT NULL,
	REPORT_COMMENT	VARCHAR2(4000)	DEFAULT ''	NULL,
	P_ID	VARCHAR2(20)	DEFAULT 0	NOT NULL,
	MEM_ID	VARCHAR2(12)	DEFAULT ''	NOT NULL
);
COMMENT ON COLUMN TB_PRODUCT_REPORT.REPORT_ID IS '신고번호';
COMMENT ON COLUMN TB_PRODUCT_REPORT.REPORT_CATEGORY IS '1.기타/2.사진/3.수입처';
COMMENT ON COLUMN TB_PRODUCT_REPORT.REPORT_COMMENT IS '신고내용';
COMMENT ON COLUMN TB_PRODUCT_REPORT.P_ID IS '상품번호';
COMMENT ON COLUMN TB_PRODUCT_REPORT.MEM_ID IS '개인회원ID';
------------------------------------------------------------------

--비회원_택배
CREATE TABLE TB_NON_PARCEL (
	PARCEL_ID	NUMBER	DEFAULT 0	NOT NULL,
	PARCEL_NAME	VARCHAR2(30)	DEFAULT ''	NULL,
	PARCEL_STATUS	CHAR(1)	DEFAULT 'N'	NULL,
	COL_DATE	DATE	DEFAULT SYSDATE	NULL,
	INVOICE_ID	NUMBER	DEFAULT 0	NOT NULL
);
COMMENT ON COLUMN TB_NON_PARCEL.PARCEL_ID IS '택배사 이름';
COMMENT ON COLUMN TB_NON_PARCEL.PARCEL_NAME IS '택배사';
COMMENT ON COLUMN TB_NON_PARCEL.PARCEL_STATUS IS 'Y/N';
COMMENT ON COLUMN TB_NON_PARCEL.COL_DATE IS '택배수거일';
COMMENT ON COLUMN TB_NON_PARCEL.INVOICE_ID IS '송장번호';
------------------------------------------------------------------

--비회원_송장
CREATE TABLE TB_NON_INVOICE (
	INVOICE_ID	NUMBER	DEFAULT 0	NOT NULL,
	PAY_STATUS	CHAR(1)	DEFAULT 'N'	NULL,
	INVOICE_REGDATE	DATE	DEFAULT SYSDATE	NULL,
	PAY_ID	NUMBER	DEFAULT 0	NOT NULL,
	OD_ID	NUMBER	DEFAULT 0	NOT NULL
);
COMMENT ON COLUMN TB_NON_INVOICE.INVOICE_ID IS '송장번호';
COMMENT ON COLUMN TB_NON_INVOICE.PAY_STATUS IS 'Y/N';
COMMENT ON COLUMN TB_NON_INVOICE.INVOICE_REGDATE IS '송장등록일';
COMMENT ON COLUMN TB_NON_INVOICE.PAY_ID IS '결제번호';
COMMENT ON COLUMN TB_NON_INVOICE.OD_ID IS '주문상세정보';
------------------------------------------------------------------

--2차옵션
CREATE TABLE TB_2ND_OPTION (
	OPTION_CON	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	OPTION_2ND_ID	VARCHAR2(50)	DEFAULT ''	NOT NULL,
	OPTION_2ND_CONTENT	VARCHAR2(100)	DEFAULT ''	NOT NULL,
	OPTION_2ND_PRICE	NUMBER	DEFAULT 0	NULL,
	OPTION_2ND_STOCK	NUMBER	DEFAULT 0	NOT NULL
);
COMMENT ON COLUMN TB_2ND_OPTION.OPTION_CON IS '옵션내용아이디';
COMMENT ON COLUMN TB_2ND_OPTION.OPTION_2ND_ID IS '옵션아이디';
COMMENT ON COLUMN TB_2ND_OPTION.OPTION_2ND_CONTENT IS '내용';
COMMENT ON COLUMN TB_2ND_OPTION.OPTION_2ND_PRICE IS '가격';
COMMENT ON COLUMN TB_2ND_OPTION.OPTION_2ND_STOCK IS '재고';
------------------------------------------------------------------

--비회원_결제
CREATE TABLE TB_NON_PAYMENT (
	PAY_ID	NUMBER	DEFAULT 0	NOT NULL,
	OD_ID	NUMBER	DEFAULT 0	NOT NULL,
	TOTAL_PAY	NUMBER	DEFAULT 0	NULL,
	PAY_DATE	DATE	DEFAULT SYSDATE	NULL
);
COMMENT ON COLUMN TB_NON_PAYMENT.PAY_ID IS '결제번호';
COMMENT ON COLUMN TB_NON_PAYMENT.OD_ID IS '주문상세정보';
COMMENT ON COLUMN TB_NON_PAYMENT.TOTAL_PAY IS '총결제금액';
COMMENT ON COLUMN TB_NON_PAYMENT.PAY_DATE IS '결제일';
------------------------------------------------------------------

-----------------------------키생성-------------------------------------
ALTER TABLE TB_SELLER ADD CONSTRAINT PK_TB_SELLER PRIMARY KEY (
	SEL_ID
);
ALTER TABLE TB_MEMBER ADD CONSTRAINT PK_TB_MEMBER PRIMARY KEY (
	MEM_ID
);
ALTER TABLE TB_INQUIRY ADD CONSTRAINT PK_TB_INQUIRY PRIMARY KEY (
	INQUIRY_ID
);
ALTER TABLE TB_REVIEW ADD CONSTRAINT PK_TB_REVIEW PRIMARY KEY (
	REVIEW_ID,
	P_ID
);
ALTER TABLE TB_MEM_INVOICE ADD CONSTRAINT PK_TB_MEM_INVOICE PRIMARY KEY (
	INVOICE_ID
);
ALTER TABLE TB_ADM_INQ ADD CONSTRAINT PK_TB_ADM_INQ PRIMARY KEY (
	ADM_INQ_NUMBER
);
ALTER TABLE TB_PRODUCT ADD CONSTRAINT PK_TB_PRODUCT PRIMARY KEY (
	P_ID
);
ALTER TABLE TB_MEM_PARCEL ADD CONSTRAINT PK_TB_MEM_PARCEL PRIMARY KEY (
	PARCEL_ID
);
ALTER TABLE TB_NON_MEMBER_ORDER ADD CONSTRAINT PK_TB_NON_MEMBER_ORDER PRIMARY KEY (
	ORD_ID
);
ALTER TABLE TB_NOTICE ADD CONSTRAINT PK_TB_NOTICE PRIMARY KEY (
	NOTICE_ID
);
ALTER TABLE TB_FAQ ADD CONSTRAINT PK_TB_FAQ PRIMARY KEY (
	FAQ_ID
);
ALTER TABLE TB_BANNER ADD CONSTRAINT PK_TB_BANNER PRIMARY KEY (
	BANNER_ID
);
ALTER TABLE TB_COUPON ADD CONSTRAINT PK_TB_COUPON PRIMARY KEY (
	COU_ID
);

ALTER TABLE TB_MEM_ORDER ADD CONSTRAINT PK_TB_MEM_ORDER PRIMARY KEY (
	ORD_ID,
	MEM_ID
);
ALTER TABLE TB_MEM_ORDER_DETAIL ADD CONSTRAINT PK_TB_MEM_ORDER_DETAIL PRIMARY KEY (
	OD_ID
);
ALTER TABLE TB_OWNED_COUPON ADD CONSTRAINT PK_TB_OWNED_COUPON PRIMARY KEY (
	MEM_ID,
	COU_ID
);
ALTER TABLE TB_VERIFICATION ADD CONSTRAINT PK_TB_VERIFICATION PRIMARY KEY (
	VERIF_ID,
	MEM_ID
);

ALTER TABLE TB_INQUIRY_PICTURE ADD CONSTRAINT PK_TB_INQUIRY_PICTURE PRIMARY KEY (
	INQUIRY_PICTURE_ID
);
ALTER TABLE TB_PRODUCT_IMG ADD CONSTRAINT PK_TB_PRODUCT_IMG PRIMARY KEY (
	P_ID
);
ALTER TABLE TB_1ST_OPTION ADD CONSTRAINT PK_TB_1ST_OPTION PRIMARY KEY (
	OPTION_ID
);
ALTER TABLE TB_DISCOUNT ADD CONSTRAINT PK_TB_DISCOUNT PRIMARY KEY (
	P_ID
);
ALTER TABLE TB_MEM_CARD ADD CONSTRAINT PK_TB_MEM_CARD PRIMARY KEY (
	OD_ID
);
ALTER TABLE TB_NON_MEMBER_ORDER_DETAIL ADD CONSTRAINT PK_TB_NON_MEMBER_ORDER_DETAIL PRIMARY KEY (
	OD_ID
);
ALTER TABLE TB_CART ADD CONSTRAINT PK_TB_CART PRIMARY KEY (
	MEM_ID,
	P_ID
);
ALTER TABLE TB_MEM_REFUND ADD CONSTRAINT PK_TB_MEM_REFUND PRIMARY KEY (
	OD_ID
);
ALTER TABLE TB_NON_REFUND ADD CONSTRAINT PK_TB_NON_REFUND PRIMARY KEY (
	OD_ID
);
ALTER TABLE TB_MEM_PAYMENT ADD CONSTRAINT PK_TB_MEM_PAYMENT PRIMARY KEY (
	PAY_ID,
	OD_ID
);
ALTER TABLE TB_REVIEW_LIKE ADD CONSTRAINT PK_TB_REVIEW_LIKE PRIMARY KEY (
	MEM_ID,
	REVIEW_ID
);
ALTER TABLE TB_NON_CARD ADD CONSTRAINT PK_TB_NON_CARD PRIMARY KEY (
	OD_ID
);
ALTER TABLE TB_BOOKMARK ADD CONSTRAINT PK_TB_BOOKMARK PRIMARY KEY (
	MEM_ID,
	SEL_ID
);
ALTER TABLE TB_WISHLIST ADD CONSTRAINT PK_TB_WISHLIST PRIMARY KEY (
	MEM_ID,
	P_ID
);
ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_TB_CATEGORY PRIMARY KEY (
	CATEGORY_SMALL
);
ALTER TABLE TB_PRODUCT_REPORT ADD CONSTRAINT PK_TB_PRODUCT_REPORT PRIMARY KEY (
	REPORT_ID
);
ALTER TABLE TB_NON_PARCEL ADD CONSTRAINT PK_TB_NON_PARCEL PRIMARY KEY (
	PARCEL_ID
);
ALTER TABLE TB_NON_INVOICE ADD CONSTRAINT PK_TB_NON_INVOICE PRIMARY KEY (
	INVOICE_ID
);
ALTER TABLE TB_2ND_OPTION ADD CONSTRAINT PK_TB_2ND_OPTION PRIMARY KEY (
	OPTION_CON,
	OPTION_2ND_ID
);
ALTER TABLE TB_NON_PAYMENT ADD CONSTRAINT PK_TB_NON_PAYMENT PRIMARY KEY (
	PAY_ID,
	OD_ID
);
ALTER TABLE TB_REVIEW_COMMENT ADD CONSTRAINT PK_TB_REVIEW_COMMENT PRIMARY KEY (
	COMMENT_NO
);

ALTER TABLE TB_REVIEW ADD CONSTRAINT FK_PRODUCT_REVIEW FOREIGN KEY (
	P_ID
)REFERENCES TB_PRODUCT (
	P_ID
);
ALTER TABLE TB_MEM_ORDER ADD CONSTRAINT FK_MEMBER_RDER FOREIGN KEY (
	MEM_ID
)REFERENCES TB_MEMBER (
	MEM_ID
);
ALTER TABLE TB_OWNED_COUPON ADD CONSTRAINT FK_MEMBER_OWNED_COUPON FOREIGN KEY (
	MEM_ID
)REFERENCES TB_MEMBER (
	MEM_ID
);
ALTER TABLE TB_OWNED_COUPON ADD CONSTRAINT FK_COUPON_OWNED_COUPON FOREIGN KEY (
	COU_ID
)REFERENCES TB_COUPON (
	COU_ID
);
ALTER TABLE TB_VERIFICATION ADD CONSTRAINT FK_MEMBER_VERIFICATION FOREIGN KEY (
	MEM_ID
)REFERENCES TB_MEMBER (
	MEM_ID
);
ALTER TABLE TB_SEARCH ADD CONSTRAINT FK_TB_MEMBER_TB_SEARCH FOREIGN KEY (
	MEM_ID
)REFERENCES TB_MEMBER (
	MEM_ID
);
ALTER TABLE TB_INQUIRY_PICTURE ADD CONSTRAINT FK_INQUIRY_PICTURE FOREIGN KEY (
	INQUIRY_PICTURE_ID
)REFERENCES TB_INQUIRY (
	INQUIRY_ID
);
ALTER TABLE TB_PRODUCT_IMG ADD CONSTRAINT FK_PRODUCT_PRODUCT_IMG FOREIGN KEY (
	P_ID
)REFERENCES TB_PRODUCT (
	P_ID
);
ALTER TABLE TB_DISCOUNT ADD CONSTRAINT FK_PRODUCT_TB_DISCOUNT FOREIGN KEY (
	P_ID
)REFERENCES TB_PRODUCT (
	P_ID
);
ALTER TABLE TB_MEM_CARD ADD CONSTRAINT FK_TB_DE_CARD FOREIGN KEY (
	OD_ID
)REFERENCES TB_MEM_ORDER_DETAIL (
	OD_ID
);
ALTER TABLE TB_CART ADD CONSTRAINT FK_TB_MEMBER_CART FOREIGN KEY (
	MEM_ID
)REFERENCES TB_MEMBER (
	MEM_ID
);
ALTER TABLE TB_CART ADD CONSTRAINT FK_TB_PRODUCT_CART FOREIGN KEY (
	P_ID
)REFERENCES TB_PRODUCT (
	P_ID
);
ALTER TABLE TB_MEM_REFUND ADD CONSTRAINT FK_MEM_ORDER_DETAIL_REFUND FOREIGN KEY (
	OD_ID
)REFERENCES TB_MEM_ORDER_DETAIL (
	OD_ID
);
ALTER TABLE TB_NON_REFUND ADD CONSTRAINT FK_NON_DETAIL_PAYMENT FOREIGN KEY (
	OD_ID
)REFERENCES TB_NON_MEMBER_ORDER_DETAIL (
	OD_ID
);
ALTER TABLE TB_MEM_PAYMENT ADD CONSTRAINT FK_MEM_DETAIL_PAYMENT FOREIGN KEY (
	OD_ID
)REFERENCES TB_MEM_ORDER_DETAIL (
	OD_ID
);
ALTER TABLE TB_REVIEW_LIKE ADD CONSTRAINT FK_TB_MEMBER_REVIEW_LIKE FOREIGN KEY (
	MEM_ID
)REFERENCES TB_MEMBER (
	MEM_ID
);
--ALTER TABLE TB_REVIEW_LIKE ADD CONSTRAINT FK_TB_REVIEW_LIKE_REVIEW  FOREIGN KEY (
--	REVIEW_ID
--)REFERENCES TB_REVIEW (
--	REVIEW_ID
--);
ALTER TABLE TB_NON_CARD ADD CONSTRAINT FK_TB_NON_DETAILCARD FOREIGN KEY (
	OD_ID
)REFERENCES TB_NON_MEMBER_ORDER_DETAIL (
	OD_ID
);
ALTER TABLE TB_BOOKMARK ADD CONSTRAINT FK_TB_MEMBER_TO_TB_BOOKMARK_1 FOREIGN KEY (
	MEM_ID
)REFERENCES TB_MEMBER (
	MEM_ID
);
ALTER TABLE TB_BOOKMARK ADD CONSTRAINT FK_TB_SEL_BOOKMARK FOREIGN KEY (
	SEL_ID
)REFERENCES TB_SELLER (
	SEL_ID
);
ALTER TABLE TB_WISHLIST ADD CONSTRAINT FK_TB_WISHLIST FOREIGN KEY (
	MEM_ID
)REFERENCES TB_MEMBER (
	MEM_ID
);
ALTER TABLE TB_WISHLIST ADD CONSTRAINT FK_TB_PRODUCT_WISHLIST FOREIGN KEY (
	P_ID
)REFERENCES TB_PRODUCT (
	P_ID
);
ALTER TABLE TB_2ND_OPTION ADD CONSTRAINT FK_TB_OPTION FOREIGN KEY (
	OPTION_2ND_ID
)REFERENCES TB_1ST_OPTION (
	OPTION_ID
);
ALTER TABLE TB_NON_PAYMENT ADD CONSTRAINT FK_DETAIL_PAYMENY FOREIGN KEY (
	OD_ID
)REFERENCES TB_NON_MEMBER_ORDER_DETAIL (
	OD_ID
);
--
--ALTER TABLE TB_SEARCH ADD CONSTRAINT FK_SEARCH_MEM FOREIGN KEY(
--    MEM_ID
--)REFERENCES TB_SEARCH(
--    MEM_ID
--);

--ALTER TABLE TB_REVIEW_COMMENT ADD CONSTRAINT FK_REVIEW_COMMENT_MESSAGE FOREGN KEY(
--    REVIEW_ID
--)REFERENCES TB_REVIEW(
--    REVIEW_ID
--);
-------------------------------------------------------------------------------

COMMIT;